; Pikachu happiness modifiers
	const_def 1
	const PIKAHAPPY_LEVELUP
	const PIKAHAPPY_USEDITEM
	const PIKAHAPPY_USEDXITEM
	const PIKAHAPPY_GYMLEADER
	const PIKAHAPPY_USEDTMHM
	const PIKAHAPPY_WALKING
	const PIKAHAPPY_DEPOSITED
	const PIKAHAPPY_FAINTED
	const PIKAHAPPY_PSNFNT
	const PIKAHAPPY_CARELESSTRAINER
	const PIKAHAPPY_TRADE

; Starter Pikachu emotion commands constants
	const_def
	const PIKAEMOTION_DUMMY1
	const PIKAEMOTION_PRINTTEXT
	const PIKAEMOTION_PLAYPCMSOUNDCLIP
	const PIKAEMOTION_DOEMOTIONBUBBLE
	const PIKAEMOTION_4
	const PIKAEMOTION_5
	const PIKAEMOTION_SUBCMD
	const PIKAEMOTION_DELAYFRAMES
	const PIKAEMOTION_DUMMY2
	const PIKAEMOTION_9
	const PIKAEMOTION_DUMMY3

	const_def
	const PIKAEMOTION_SUBCMD_LOADEXTRAPIKASPRITES
	const PIKAEMOTION_SUBCMD_LOADFONT
	const PIKAEMOTION_SUBCMD_SHOWMAPVIEW
	const PIKAEMOTION_SUBCMD_WAITBUTTONPRESS
	const PIKAEMOTION_SUBCMD_CHECKPEWTERCENTER
	const PIKAEMOTION_SUBCMD_CHECKLAVENDERTOWER
	const PIKAEMOTION_SUBCMD_CHECKBILLSHOUSE

; Pikachu movement constants
	const_def
	const PIKASTEPDIR_DOWN
	const PIKASTEPDIR_UP
	const PIKASTEPDIR_LEFT
	const PIKASTEPDIR_RIGHT
	const PIKASTEPDIR_DOWN_LEFT
	const PIKASTEPDIR_DOWN_RIGHT
	const PIKASTEPDIR_UP_LEFT
	const PIKASTEPDIR_UP_RIGHT

; wPikachuSpawnStateFlags bits
	const_def
	const BIT_PIKACHU_SPAWN_0
	const BIT_PIKACHU_SPAWN_1
	const BIT_PIKACHU_SPAWN_2
	const BIT_PIKACHU_SPAWN_3
	const BIT_PIKACHU_SPAWN_4
	const BIT_PIKACHU_SPAWN_FOLLOWING
	const BIT_PIKACHU_SPAWN_SURFING
	const BIT_PIKACHU_SPAWN_STARTER

; wPikachuMapScriptFlags bits
	const_def
	const BIT_PIKACHU_MAP_PAUSE_IGT
	const BIT_PIKACHU_MAP_SURF_SELECT
	const BIT_PIKACHU_MAP_2
	const BIT_PIKACHU_MAP_3
	const BIT_PIKACHU_MAP_4
	const BIT_PIKACHU_MAP_5
	const BIT_PIKACHU_MAP_6
	const BIT_PIKACHU_MAP_SCRIPT_ACTIVE

; Pikachu movement commands
DEF PIKAMOVEMENT_DELAY       EQU $00
DEF PIKAMOVEMENT_STEP_DOWN   EQU $1d
DEF PIKAMOVEMENT_STEP_UP     EQU $1e
DEF PIKAMOVEMENT_STEP_LEFT   EQU $1f
DEF PIKAMOVEMENT_STEP_RIGHT  EQU $20
DEF PIKAMOVEMENT_LOOK_DOWN   EQU $35
DEF PIKAMOVEMENT_LOOK_UP     EQU $36
DEF PIKAMOVEMENT_LOOK_LEFT   EQU $37
DEF PIKAMOVEMENT_LOOK_RIGHT  EQU $38
DEF PIKAMOVEMENT_END         EQU $3f
