; animated_object struct members (see macros/wram.asm)
ANIM_OBJ_INDEX           EQUS "wAnimatedObject0Index - wAnimatedObject0"
ANIM_OBJ_FRAME_SET       EQUS "wAnimatedObject0FramesetID - wAnimatedObject0"
ANIM_OBJ_CALLBACK        EQUS "wAnimatedObject0AnimSeqID - wAnimatedObject0"
ANIM_OBJ_TILE            EQUS "wAnimatedObject0TileID - wAnimatedObject0"
ANIM_OBJ_X_COORD         EQUS "wAnimatedObject0XCoord - wAnimatedObject0"
ANIM_OBJ_Y_COORD         EQUS "wAnimatedObject0YCoord - wAnimatedObject0"
ANIM_OBJ_X_OFFSET        EQUS "wAnimatedObject0XOffset - wAnimatedObject0"
ANIM_OBJ_Y_OFFSET        EQUS "wAnimatedObject0YOffset - wAnimatedObject0"
ANIM_OBJ_DURATION        EQUS "wAnimatedObject0Duration - wAnimatedObject0"
ANIM_OBJ_DURATION_OFFSET EQUS "wAnimatedObject0DurationOffset - wAnimatedObject0"
ANIM_OBJ_FRAME_IDX       EQUS "wAnimatedObject0FrameIndex - wAnimatedObject0"
ANIM_OBJ_FIELD_B         EQUS "wAnimatedObject0FieldB - wAnimatedObject0"
ANIM_OBJ_FIELD_C         EQUS "wAnimatedObject0FieldC - wAnimatedObject0"
ANIM_OBJ_FIELD_D         EQUS "wAnimatedObject0FieldD - wAnimatedObject0"
ANIM_OBJ_FIELD_E         EQUS "wAnimatedObject0FieldE - wAnimatedObject0"
ANIM_OBJ_FIELD_F         EQUS "wAnimatedObject0FieldF - wAnimatedObject0"
