; const_value = 1	
	
	; tx_pre_const CardKeySuccessText                   ; 01
	; tx_pre_const CardKeyFailText                      ; 02
	; tx_pre_const RedBedroomPCText                     ; 03
	; tx_pre_const RedBedroomSNESText                   ; 04
	; tx_pre_const PushStartText                        ; 05
	; tx_pre_const SaveOptionText                       ; 06
	; tx_pre_const StrengthsAndWeaknessesText           ; 07
	; tx_pre_const OakLabEmailText                      ; 08
	; tx_pre_const AerodactylFossilText                 ; 09
	; tx_pre_const Route15UpstairsBinocularsText        ; 0A
	; tx_pre_const KabutopsFossilText                   ; 0B
	; tx_pre_const FanClubRapidashText                  ; 0C
	; tx_pre_const FanClubFearowText                    ; 0D
	; tx_pre_const GymStatueText1                       ; 0E
	; tx_pre_const GymStatueText2                       ; 0F
	; tx_pre_const BookcaseText                         ; 10
	; tx_pre_const ViridianCityPokecenterBenchGuyText   ; 11
	; tx_pre_const PewterCityPokecenterBenchGuyText     ; 12
	; tx_pre_const CeruleanCityPokecenterBenchGuyText   ; 13
	; tx_pre_const LavenderCityPokecenterBenchGuyText   ; 14
	; tx_pre_const VermilionCityPokecenterBenchGuyText  ; 15
	; tx_pre_const CeladonCityPokecenterBenchGuyText    ; 16
	; tx_pre_const CeladonCityHotelText                 ; 17
	; tx_pre_const FuchsiaCityPokecenterBenchGuyText    ; 18
	; tx_pre_const CinnabarIslandPokecenterBenchGuyText ; 19
	; tx_pre_const SaffronCityPokecenterBenchGuyText    ; 1A
	; tx_pre_const MtMoonPokecenterBenchGuyText         ; 1B
	; tx_pre_const RockTunnelPokecenterBenchGuyText     ; 1C
	; tx_pre_const UnusedBenchGuyText1                  ; 1D
	; tx_pre_const UnusedBenchGuyText2                  ; 1E
	; tx_pre_const UnusedBenchGuyText3                  ; 1F
	; tx_pre_const UnusedPredefText                     ; 20
	; tx_pre_const PokemonCenterPCText                  ; 21
	; tx_pre_const ViridianSchoolNotebook               ; 22
	; tx_pre_const ViridianSchoolBlackboard             ; 23
	; tx_pre_const FakeTextPredef22
	; tx_pre_const FakeTextPredef23
	; tx_pre_const JustAMomentText                      ; 24
	; tx_pre_const OpenBillsPCText                      ; 25
	; tx_pre_const FoundHiddenItemText                  ; 26
	; tx_pre_const HiddenItemBagFullText                ; 27
	; tx_pre_const VermilionGymTrashText                ; 28
	; tx_pre_const IndigoPlateauHQText                  ; 29
	; tx_pre_const GameCornerOutOfOrderText             ; 2A
	; tx_pre_const GameCornerOutToLunchText             ; 2B
	; tx_pre_const GameCornerSomeonesKeysText           ; 2C
	; tx_pre_const FoundHiddenCoinsText                 ; 2D
	; tx_pre_const DroppedHiddenCoinsText               ; 2E
	; tx_pre_const BillsHouseMonitorText                ; 2F
	; tx_pre_const BillsHouseInitiatedText              ; 30
	; tx_pre_const BillsHousePokemonList                ; 31
	; tx_pre_const MagazinesText                        ; 32
	; tx_pre_const CinnabarGymQuiz                      ; 33
	; tx_pre_const GameCornerNoCoinsText                ; 34
	; tx_pre_const GameCornerCoinCaseText               ; 35
	; tx_pre_const LinkCableHelp                        ; 36
	; tx_pre_const TMNotebook                           ; 37
	; tx_pre_const FightingDojoText                     ; 38
	; tx_pre_const EnemiesOnEverySideText               ; 39
	; tx_pre_const WhatGoesAroundComesAroundText        ; 3A
	; tx_pre_const NewBicycleText                       ; 3B
	; tx_pre_const IndigoPlateauStatues                 ; 3C XXX unused
	; tx_pre_const VermilionGymTrashSuccesText1         ; 3D
	; tx_pre_const VermilionGymTrashSuccesText2         ; 3E
	; tx_pre_const VermilionGymTrashSuccesText3         ; 3F
	; tx_pre_const VermilionGymTrashFailText            ; 40
	; tx_pre_const TownMapText                          ; 41
	; tx_pre_const BookOrSculptureText                  ; 42
	; tx_pre_const ElevatorText                         ; 43
	; tx_pre_const PokemonStuffText                     ; 44
