#!/usr/bin/env python3
"""Generate all dos_port/assets/*.inc files from pret binary sources.

Supersedes tools/gen_overworld_assets.py — run this instead.

Sources required (built by 'make' in repo root):
  gfx/tilesets/*.2bpp       — built by rgbgfx from .png files
  gfx/blocksets/*.bst       — checked-in binary blockset data
  maps/*.blk                — checked-in binary map block layouts
  gfx/sprites/red.2bpp      — built by rgbgfx
  gfx/sprites/*.2bpp        — NPC sprite sheets

Run from the repo root:
    python3 tools/gen_all_assets.py

Or via make:
    make -C dos_port assets
"""
import sys
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
ASSETS = ROOT / "dos_port" / "assets"
GFX_TILESETS = ROOT / "gfx" / "tilesets"
GFX_BLOCKSETS = ROOT / "gfx" / "blocksets"
MAPS_DIR = ROOT / "maps"
GFX_SPRITES = ROOT / "gfx" / "sprites"
COLL_SRC = ROOT / "data" / "tilesets" / "collision_tile_ids.asm"
SPRITE_CONSTANTS = ROOT / "constants" / "sprite_constants.asm"
MAPS_OBJECTS_DIR = ROOT / "data" / "maps" / "objects"
NPC_SPRITES_DIR = ASSETS / "npc_sprites"

# ---------------------------------------------------------------------------
# Tileset table: (id, canonical_name, gfx_stem, blocks_stem, coll_label)
#   canonical_name   — used for inc file labels (e.g. "reds_house" → reds_house_gfx)
#   gfx_stem         — stem of .2bpp file in gfx/tilesets/
#   blocks_stem      — stem of .bst file in gfx/blocksets/
#   coll_label       — label prefix in collision_tile_ids.asm (without _Coll::)
# Shared tilesets (same gfx/blocks/coll) are listed with the canonical name of
# the primary tileset; the dispatch tables in gen_map_headers.py reuse the label.
# ---------------------------------------------------------------------------
TILESETS = [
    # id  canonical_name  gfx_stem      blocks_stem   coll_label
    ( 0, "overworld",    "overworld",   "overworld",  "Overworld"),
    ( 1, "reds_house",   "reds_house",  "reds_house",  "RedsHouse1"),
    ( 2, "pokecenter",   "pokecenter",  "pokecenter",  "Mart"),
    ( 3, "forest",       "forest",      "forest",      "Forest"),
    ( 4, "reds_house",   "reds_house",  "reds_house",  "RedsHouse2"),  # same GFX as RedsHouse1
    ( 5, "gym",          "gym",         "gym",         "Dojo"),
    ( 6, "pokecenter",   "pokecenter",  "pokecenter",  "Pokecenter"),  # same GFX as Mart
    ( 7, "gym",          "gym",         "gym",         "Gym"),         # same GFX as Dojo
    ( 8, "house",        "house",       "house",       "House"),
    ( 9, "gate",         "gate",        "gate",        "ForestGate"),
    (10, "gate",         "gate",        "gate",        "Museum"),      # same GFX as Gate
    (11, "underground",  "underground", "underground", "Underground"),
    (12, "gate",         "gate",        "gate",        "Gate"),        # same GFX as ForestGate
    (13, "ship",         "ship",        "ship",        "Ship"),
    (14, "ship_port",    "ship_port",   "ship_port",   "ShipPort"),
    (15, "cemetery",     "cemetery",    "cemetery",    "Cemetery"),
    (16, "interior",     "interior",    "interior",    "Interior"),
    (17, "cavern",       "cavern",      "cavern",      "Cavern"),
    (18, "lobby",        "lobby",       "lobby",       "Lobby"),
    (19, "mansion",      "mansion",     "mansion",     "Mansion"),
    (20, "lab",          "lab",         "lab",         "Lab"),
    (21, "club",         "club",        "club",        "Club"),
    (22, "facility",     "facility",    "facility",    "Facility"),
    (23, "plateau",      "plateau",     "plateau",     "Plateau"),
    (24, "beach_house",  "beach_house", "beach_house", "BeachHouse"),
]


def write_inc(dst: Path, label: str, data: bytes, comment: str = ""):
    lines = [f"; {dst.name} — generated by tools/gen_all_assets.py. DO NOT EDIT BY HAND."]
    if comment:
        lines.append(f"; {comment}")
    lines += ["", f"{label}:"]
    for i in range(0, len(data), 16):
        lines.append("    db " + ", ".join(f"0x{b:02X}" for b in data[i:i+16]))
    lines += [
        f"{label}_end:",
        f"{label.upper()}_SIZE equ {label}_end - {label}",
        "",
    ]
    dst.write_text("\n".join(lines) + "\n")
    print(f"  wrote {dst} ({len(data)} bytes)")


def parse_coll_list(label_prefix: str) -> bytes:
    """Extract <label_prefix>_Coll:: coll_tiles ... from collision_tile_ids.asm."""
    want = f"{label_prefix}_Coll::"
    lines = COLL_SRC.read_text().splitlines()
    seen = False
    for line in lines:
        s = line.strip()
        if s.startswith(want):
            seen = True
        if seen and "coll_tiles" in s:
            args = s.split("coll_tiles", 1)[1]
            ids = [int(tok.strip().replace("$", "0x"), 16)
                   for tok in args.split(",") if tok.strip()]
            return bytes(ids) + b"\xff"
    raise SystemExit(f"ERROR: {want} not found in {COLL_SRC}")


def to_snake(pascal: str) -> str:
    """PascalCase → snake_case: OaksLab → oaks_lab, Route1 → route1."""
    s = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", pascal)
    return s.lower()


def parse_sprite_constants() -> dict:
    """Parse constants/sprite_constants.asm → {SPRITE_FOO: id} (sequential const_def)."""
    result = {}
    sprite_id = 0
    for line in SPRITE_CONSTANTS.read_text().splitlines():
        m = re.match(r'\s*const\s+(SPRITE_\w+)', line)
        if m:
            result[m.group(1)] = sprite_id
            sprite_id += 1
    return result


def enumerate_npc_sprites() -> list:
    """Scan all data/maps/objects/*.asm for object_event SPRITE_* tokens.

    Returns a sorted list of (sprite_id, stem, const_name) tuples for every
    unique sprite constant used on any map.  stem is the .2bpp filename stem
    (SPRITE_COOLTRAINER_F → cooltrainer_f).
    """
    sprite_map = parse_sprite_constants()
    used: set = set()
    for obj_file in sorted(MAPS_OBJECTS_DIR.glob("*.asm")):
        for line in obj_file.read_text().splitlines():
            m = re.search(r'\bobject_event\b[^;]*(SPRITE_\w+)', line)
            if m:
                name = m.group(1)
                if name in sprite_map:
                    used.add(name)
                else:
                    print(f"WARNING: unknown sprite constant {name!r} in {obj_file.name}",
                          file=sys.stderr)
    result = []
    for name in used:
        sid = sprite_map[name]
        stem = name[len("SPRITE_"):].lower()
        result.append((sid, stem, name))
    result.sort()
    return result


def main():
    ASSETS.mkdir(parents=True, exist_ok=True)

    # ------------------------------------------------------------------
    # 1. Tileset GFX / blocks / coll — one inc file per unique source
    # ------------------------------------------------------------------
    seen_canonical = set()
    for tid, canonical, gfx_stem, blocks_stem, coll_label in TILESETS:
        if canonical in seen_canonical:
            continue
        seen_canonical.add(canonical)

        gfx_src    = GFX_TILESETS / f"{gfx_stem}.2bpp"
        blocks_src = GFX_BLOCKSETS / f"{blocks_stem}.bst"

        if not gfx_src.exists():
            print(f"WARNING: {gfx_src} missing — run 'make' in repo root first",
                  file=sys.stderr)
            continue

        write_inc(
            ASSETS / f"{canonical}_gfx.inc",
            f"{canonical}_gfx",
            gfx_src.read_bytes(),
            f"{gfx_stem}.2bpp → [EBP+OW_GFX_GBADDR] (active tileset slot)",
        )
        write_inc(
            ASSETS / f"{canonical}_blocks.inc",
            f"{canonical}_blocks",
            blocks_src.read_bytes(),
            f"{blocks_stem}.bst → [EBP+OW_BLOCKS_GBADDR] (active blockset slot)",
        )
        write_inc(
            ASSETS / f"{canonical}_coll.inc",
            f"{canonical}_coll",
            parse_coll_list(coll_label),
            f"{coll_label}_Coll (passable tiles, $FF-terminated) → [EBP+OW_COLL_GBADDR]",
        )

    # ------------------------------------------------------------------
    # 2. Map block layouts — one inc file per .blk file
    # ------------------------------------------------------------------
    for blk_file in sorted(MAPS_DIR.glob("*.blk")):
        pascal = blk_file.stem        # e.g. "OaksLab"
        snake  = to_snake(pascal)     # e.g. "oaks_lab"
        label  = f"{snake}_blk"
        write_inc(
            ASSETS / f"{label}.inc",
            label,
            blk_file.read_bytes(),
            f"{blk_file.name} block map → [EBP+INDOOR_BLK_GBADDR] (indoor) "
            f"or fixed outdoor slot",
        )

    # ------------------------------------------------------------------
    # 3. Player sprite
    # ------------------------------------------------------------------
    player_src = GFX_SPRITES / "red.2bpp"
    if player_src.exists():
        write_inc(
            ASSETS / "player_sprite.inc",
            "player_sprite",
            player_src.read_bytes(),
            "Red overworld sprite 2bpp → [EBP+GB_VCHARS0] ($8000)",
        )

    # ------------------------------------------------------------------
    # 4. NPC sprite assets — all sprites used in any map's object_event lines.
    #
    # Per-sprite:  assets/npc_sprites/<stem>.inc  (full 24-tile sheet)
    # Master table: assets/npc_sprite_data_table.inc
    #    — %includes all per-sprite files then defines npc_sprite_data_table:
    #      a flat dd array indexed by sprite_id (0x00 … max_id).
    # ------------------------------------------------------------------
    NPC_SPRITES_DIR.mkdir(parents=True, exist_ok=True)
    used_sprites = enumerate_npc_sprites()

    if not used_sprites:
        print("WARNING: no SPRITE_* constants found in map object files", file=sys.stderr)

    max_id = max(sid for sid, _, _ in used_sprites) if used_sprites else 0
    table_size = max_id + 1

    # Map sprite_id → stem for used sprites
    by_id: dict = {sid: (stem, name) for sid, stem, name in used_sprites}

    FULL_SHEET = 384  # 24 tiles × 16 bytes; LoadNPCSpriteTiles always copies this much

    # Per-sprite full-sheet inc files
    missing: set = set()
    for sid, stem, name in used_sprites:
        src = GFX_SPRITES / f"{stem}.2bpp"
        if not src.exists():
            print(f"WARNING: {src} missing for {name} (id=0x{sid:02X}), "
                  "emitting dd 0 in table", file=sys.stderr)
            missing.add(sid)
            continue
        data = src.read_bytes()
        note = ""
        if len(data) < FULL_SHEET:
            # Sprites smaller than 24 tiles (items, single-pose NPCs): pad with
            # zeros so LoadNPCSpriteTiles's two rep movsb calls always find
            # FULL_SHEET bytes.  Walk tiles will be zeroed (invisible) which is
            # correct for STAY-only sprites.
            note = f", padded from {len(data)} bytes"
            data = data + bytes(FULL_SHEET - len(data))
        write_inc(
            NPC_SPRITES_DIR / f"{stem}.inc",
            f"npc_{stem}",
            data,
            f"{name} (0x{sid:02X}) sprite sheet (24 tiles: [0-11]=still, "
            f"[12-23]=walk{note})",
        )

    # Master data table: %includes + flat pointer array
    table_lines = [
        "; npc_sprite_data_table.inc — generated by tools/gen_all_assets.py. DO NOT EDIT BY HAND.",
        "; Flat dd array indexed by sprite_id (0 = no asset / not used on any map).",
        "; Included from map_sprites.asm in section .data.",
        "",
    ]
    for sid, stem, name in used_sprites:
        if sid not in missing:
            table_lines.append(f'%include "assets/npc_sprites/{stem}.inc"')
    table_lines += [
        "",
        f"NPC_SPRITE_TABLE_SIZE equ {table_size}",
        "",
        "npc_sprite_data_table:",
    ]
    for i in range(table_size):
        if i in by_id and i not in missing:
            stem, name = by_id[i]
            table_lines.append(f"    dd npc_{stem}  ; 0x{i:02X} {name}")
        else:
            comment = f"; 0x{i:02X} {by_id[i][1]}" if i in by_id else f"; 0x{i:02X} (unused)"
            table_lines.append(f"    dd 0  {comment}")
    table_lines.append("")
    (ASSETS / "npc_sprite_data_table.inc").write_text("\n".join(table_lines) + "\n")
    print(f"  wrote {ASSETS / 'npc_sprite_data_table.inc'} "
          f"({table_size} entries, {len(used_sprites) - len(missing)} sprites)")

    print("done.")


if __name__ == "__main__":
    main()
