#!/usr/bin/env python3
"""Generate all dos_port/assets/*.inc files from pret binary sources.

Supersedes tools/gen_overworld_assets.py — run this instead.

Sources required (built by 'make' in repo root):
  gfx/tilesets/*.2bpp       — built by rgbgfx from .png files
  gfx/blocksets/*.bst       — checked-in binary blockset data
  maps/*.blk                — checked-in binary map block layouts
  gfx/sprites/red.2bpp      — built by rgbgfx
  gfx/sprites/*.2bpp        — NPC sprite sheets

Run from the repo root:
    python3 tools/gen_all_assets.py

Or via make:
    make -C dos_port assets
"""
import sys
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
ASSETS = ROOT / "dos_port" / "assets"
GFX_TILESETS = ROOT / "gfx" / "tilesets"
GFX_BLOCKSETS = ROOT / "gfx" / "blocksets"
MAPS_DIR = ROOT / "maps"
GFX_SPRITES = ROOT / "gfx" / "sprites"
COLL_SRC = ROOT / "data" / "tilesets" / "collision_tile_ids.asm"

# ---------------------------------------------------------------------------
# Tileset table: (id, canonical_name, gfx_stem, blocks_stem, coll_label)
#   canonical_name   — used for inc file labels (e.g. "reds_house" → reds_house_gfx)
#   gfx_stem         — stem of .2bpp file in gfx/tilesets/
#   blocks_stem      — stem of .bst file in gfx/blocksets/
#   coll_label       — label prefix in collision_tile_ids.asm (without _Coll::)
# Shared tilesets (same gfx/blocks/coll) are listed with the canonical name of
# the primary tileset; the dispatch tables in gen_map_headers.py reuse the label.
# ---------------------------------------------------------------------------
TILESETS = [
    # id  canonical_name  gfx_stem      blocks_stem   coll_label
    ( 0, "overworld",    "overworld",   "overworld",  "Overworld"),
    ( 1, "reds_house",   "reds_house",  "reds_house",  "RedsHouse1"),
    ( 2, "pokecenter",   "pokecenter",  "pokecenter",  "Mart"),
    ( 3, "forest",       "forest",      "forest",      "Forest"),
    ( 4, "reds_house",   "reds_house",  "reds_house",  "RedsHouse2"),  # same GFX as RedsHouse1
    ( 5, "gym",          "gym",         "gym",         "Dojo"),
    ( 6, "pokecenter",   "pokecenter",  "pokecenter",  "Pokecenter"),  # same GFX as Mart
    ( 7, "gym",          "gym",         "gym",         "Gym"),         # same GFX as Dojo
    ( 8, "house",        "house",       "house",       "House"),
    ( 9, "gate",         "gate",        "gate",        "ForestGate"),
    (10, "gate",         "gate",        "gate",        "Museum"),      # same GFX as Gate
    (11, "underground",  "underground", "underground", "Underground"),
    (12, "gate",         "gate",        "gate",        "Gate"),        # same GFX as ForestGate
    (13, "ship",         "ship",        "ship",        "Ship"),
    (14, "ship_port",    "ship_port",   "ship_port",   "ShipPort"),
    (15, "cemetery",     "cemetery",    "cemetery",    "Cemetery"),
    (16, "interior",     "interior",    "interior",    "Interior"),
    (17, "cavern",       "cavern",      "cavern",      "Cavern"),
    (18, "lobby",        "lobby",       "lobby",       "Lobby"),
    (19, "mansion",      "mansion",     "mansion",     "Mansion"),
    (20, "lab",          "lab",         "lab",         "Lab"),
    (21, "club",         "club",        "club",        "Club"),
    (22, "facility",     "facility",    "facility",    "Facility"),
    (23, "plateau",      "plateau",     "plateau",     "Plateau"),
    (24, "beach_house",  "beach_house", "beach_house", "BeachHouse"),
]


def write_inc(dst: Path, label: str, data: bytes, comment: str = ""):
    lines = [f"; {dst.name} — generated by tools/gen_all_assets.py. DO NOT EDIT BY HAND."]
    if comment:
        lines.append(f"; {comment}")
    lines += ["", f"{label}:"]
    for i in range(0, len(data), 16):
        lines.append("    db " + ", ".join(f"0x{b:02X}" for b in data[i:i+16]))
    lines += [
        f"{label}_end:",
        f"{label.upper()}_SIZE equ {label}_end - {label}",
        "",
    ]
    dst.write_text("\n".join(lines) + "\n")
    print(f"  wrote {dst} ({len(data)} bytes)")


def parse_coll_list(label_prefix: str) -> bytes:
    """Extract <label_prefix>_Coll:: coll_tiles ... from collision_tile_ids.asm."""
    want = f"{label_prefix}_Coll::"
    lines = COLL_SRC.read_text().splitlines()
    seen = False
    for line in lines:
        s = line.strip()
        if s.startswith(want):
            seen = True
        if seen and "coll_tiles" in s:
            args = s.split("coll_tiles", 1)[1]
            ids = [int(tok.strip().replace("$", "0x"), 16)
                   for tok in args.split(",") if tok.strip()]
            return bytes(ids) + b"\xff"
    raise SystemExit(f"ERROR: {want} not found in {COLL_SRC}")


def to_snake(pascal: str) -> str:
    """PascalCase → snake_case: OaksLab → oaks_lab, Route1 → route1."""
    s = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", pascal)
    return s.lower()


def main():
    ASSETS.mkdir(parents=True, exist_ok=True)

    # ------------------------------------------------------------------
    # 1. Tileset GFX / blocks / coll — one inc file per unique source
    # ------------------------------------------------------------------
    seen_canonical = set()
    for tid, canonical, gfx_stem, blocks_stem, coll_label in TILESETS:
        if canonical in seen_canonical:
            continue
        seen_canonical.add(canonical)

        gfx_src    = GFX_TILESETS / f"{gfx_stem}.2bpp"
        blocks_src = GFX_BLOCKSETS / f"{blocks_stem}.bst"

        if not gfx_src.exists():
            print(f"WARNING: {gfx_src} missing — run 'make' in repo root first",
                  file=sys.stderr)
            continue

        write_inc(
            ASSETS / f"{canonical}_gfx.inc",
            f"{canonical}_gfx",
            gfx_src.read_bytes(),
            f"{gfx_stem}.2bpp → [EBP+OW_GFX_GBADDR] (active tileset slot)",
        )
        write_inc(
            ASSETS / f"{canonical}_blocks.inc",
            f"{canonical}_blocks",
            blocks_src.read_bytes(),
            f"{blocks_stem}.bst → [EBP+OW_BLOCKS_GBADDR] (active blockset slot)",
        )
        write_inc(
            ASSETS / f"{canonical}_coll.inc",
            f"{canonical}_coll",
            parse_coll_list(coll_label),
            f"{coll_label}_Coll (passable tiles, $FF-terminated) → [EBP+OW_COLL_GBADDR]",
        )

    # ------------------------------------------------------------------
    # 2. Map block layouts — one inc file per .blk file
    # ------------------------------------------------------------------
    for blk_file in sorted(MAPS_DIR.glob("*.blk")):
        pascal = blk_file.stem        # e.g. "OaksLab"
        snake  = to_snake(pascal)     # e.g. "oaks_lab"
        label  = f"{snake}_blk"
        write_inc(
            ASSETS / f"{label}.inc",
            label,
            blk_file.read_bytes(),
            f"{blk_file.name} block map → [EBP+INDOOR_BLK_GBADDR] (indoor) "
            f"or fixed outdoor slot",
        )

    # ------------------------------------------------------------------
    # 3. Sprite assets (kept from gen_overworld_assets.py)
    # ------------------------------------------------------------------
    player_src = GFX_SPRITES / "red.2bpp"
    if player_src.exists():
        write_inc(
            ASSETS / "player_sprite.inc",
            "player_sprite",
            player_src.read_bytes(),
            "Red overworld sprite 2bpp → [EBP+GB_VCHARS0] ($8000)",
        )

    for label, fname, base_offset in [
        ("npc_girl_still",   "girl",   3),
        ("npc_fisher_still", "fisher", 4),
        ("npc_oak_still",    "oak",    5),
    ]:
        src = GFX_SPRITES / f"{fname}.2bpp"
        if src.exists():
            tile_base = (base_offset - 1) * 12
            write_inc(
                ASSETS / f"{label}.inc",
                label,
                src.read_bytes()[:192],
                f"{fname} NPC still tiles (12 tiles, imageBaseOffset {base_offset}) "
                f"→ [EBP+GB_VCHARS0+0x{tile_base:02X}*16] (${0x8000 + tile_base*16:04X})",
            )

    print("done.")


if __name__ == "__main__":
    main()
