#!/usr/bin/env python3
"""Generate NASM event-flag index constants from the pret event list.

Input:  constants/event_constants.asm  (rgbds const_def/const/const_skip/const_next)
Output: dos_port/assets/event_constants.inc  (EVENT_* equ <bit index>, + NUM_EVENTS)

Each EVENT_* is a bit position in wEventFlags (W_EVENT_FLAGS). events.inc turns an
index into (byte offset, bit mask). Mirrors macros/const.asm semantics:
  const_def [start=0] [inc=1]   reset counter
  const NAME                    NAME = counter; counter += inc
  const_skip [N=1]              counter += inc*N
  const_next X                  counter = X
Also carries `DEF NAME EQU const_value [± k]` lines (NUM_EVENTS, range markers).

Run from dos_port/ or repo root:
    python3 tools/gen_event_constants.py
"""
import re
import sys
from pathlib import Path

ROOT    = Path(__file__).resolve().parent.parent.parent
SRC     = ROOT / "constants" / "event_constants.asm"
OUT     = Path(__file__).resolve().parent.parent / "assets" / "event_constants.inc"


def parse_num(tok):
    """Parse an rgbds integer literal ($hex or decimal)."""
    tok = tok.strip()
    if tok.startswith('$'):
        return int(tok[1:], 16)
    return int(tok, 0)


def main():
    value = 0          # const_value
    inc   = 1          # const_inc
    events = []        # (name, value) in source order
    defs   = []        # (name, value) for DEF ... EQU lines

    for raw in SRC.read_text(encoding='utf-8').splitlines():
        line = raw.split(';', 1)[0].strip()
        if not line:
            continue

        m = re.match(r'const_def\b\s*(\S+)?\s*,?\s*(\S+)?', line)
        if m and line.startswith('const_def'):
            value = parse_num(m.group(1)) if m.group(1) else 0
            inc   = parse_num(m.group(2)) if m.group(2) else 1
            continue

        m = re.match(r'const_next\b\s*(\S+)', line)
        if m:
            value = parse_num(m.group(1))
            continue

        m = re.match(r'const_skip\b\s*(\S+)?', line)
        if m and line.startswith('const_skip'):
            n = parse_num(m.group(1)) if m.group(1) else 1
            value += inc * n
            continue

        m = re.match(r'const\s+([A-Za-z_][A-Za-z0-9_]*)', line)
        if m:
            events.append((m.group(1), value))
            value += inc
            continue

        # DEF NAME EQU const_value [(+|-) k]
        m = re.match(r'DEF\s+([A-Za-z_]\w*)\s+EQU\s+const_value\s*([+-]\s*\d+)?', line)
        if m:
            off = int(m.group(2).replace(' ', '')) if m.group(2) else 0
            defs.append((m.group(1), value + off))
            continue

        sys.stderr.write(f'warning: unparsed line: {raw!r}\n')

    lines = [
        '; AUTO-GENERATED by dos_port/tools/gen_event_constants.py — DO NOT EDIT.',
        '; Event-flag bit indices in wEventFlags, from constants/event_constants.asm.',
        '; Use with include/events.inc: CheckEvent/SetEvent/ResetEvent EVENT_*.',
        '',
    ]
    width = max(len(n) for n, _ in events)
    for name, val in events:
        lines.append(f'{name:<{width}} equ {val}')
    lines.append('')
    lines.append('; Range markers and total (DEF ... EQU const_value in the source).')
    dwidth = max(len(n) for n, _ in defs)
    for name, val in defs:
        lines.append(f'{name:<{dwidth}} equ {val}')
    lines.append('')

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text('\n'.join(lines), encoding='utf-8')
    print(f'Wrote {OUT.relative_to(ROOT)} — {len(events)} events, '
          f'{len(defs)} markers, NUM_EVENTS={dict(defs).get("NUM_EVENTS")}')


if __name__ == '__main__':
    main()
