#!/usr/bin/env bash
# Launch the MCP-patched DOSBox-X with PKMN.EXE + start the MCP server.
#
# Usage:
#   tools/run_with_mcp.sh [extra make flags for PKMN.EXE build]
#
# Steps:
#   1. Build PKMN.EXE (SKIP_TITLE=1 by default for fast boot to overworld)
#   2. Launch tools/dosbox-x-mcp/dosbox-x with a dosbox-x.conf that enables
#      the heavy debugger and the MCP socket.
#   3. Print instructions to connect Claude Code.
#
# The MCP server (tools/dosbox_mcp/server.py) is registered via
# .claude/settings.json and started automatically by Claude Code.
# You don't need to start it manually.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
DOSPORT="$(cd "$SCRIPT_DIR/.." && pwd)"
BINARY="${SCRIPT_DIR}/dosbox-x-mcp/dosbox-x"
SOCK_PATH="/tmp/dosbox-mcp.sock"

if [ ! -x "$BINARY" ]; then
    echo "ERROR: patched binary not found at $BINARY"
    echo "Run: dos_port/tools/build_dosbox_mcp.sh"
    exit 1
fi

# Build PKMN.EXE if needed
echo "Building PKMN.EXE..."
make -C "$DOSPORT" SKIP_TITLE=1 "${@}"

# Write a temporary dosbox-x.conf with MCP socket enabled.
# We use the user's existing dosbox-x conf as a base and override [log] section.
CONF="/tmp/dosbox-mcp-$$.conf"
cat > "$CONF" <<EOF
# Auto-generated by run_with_mcp.sh — do not edit
[dosbox]
machine=vgaonly

[cpu]
cputype=386_prefetch
core=normal

[log]
# MCP debug socket — lets Claude Code drive the debugger live
mcp_socket=${SOCK_PATH}

[autoexec]
mount c "${DOSPORT}"
c:
PKMN.EXE
EOF

echo ""
echo "Starting MCP-patched DOSBox-X..."
echo "  Socket:  ${SOCK_PATH}"
echo "  Binary:  ${BINARY}"
echo "  PKMN.EXE starts paused at BIOS entry so you can set breakpoints first."
echo ""
echo "From Claude Code: use get_registers(), set_breakpoint('LoadWarpDestination'),"
echo "  continue_exec(), gb_read(), dump_frame() etc."
echo ""

# -break-start: pause at BIOS entry so MCP can set breakpoints before game runs.
# The socket is started from DEBUG_Init so it is ready as soon as DOSBox-X opens.
exec "$BINARY" \
    -defaultdir "$DOSPORT" \
    -conf "$CONF" \
    -break-start
