; map_sprites.asm — NPC sprite slot initialization and tile loading.
;
; Faithful translation (pret cross-reference):
;   InitMapSprites      engine/overworld/map_sprites.asm:InitMapSprites /
;                       InitOutsideMapSprites / LoadSpriteSetFromMapHeader
;   LoadNPCSpriteTiles  engine/overworld/map_sprites.asm:LoadMapSpriteTilePatterns /
;                       ReadSpriteSheetData
;
; After LoadMapHeader sets W_OBJECT_DATA_PTR_TEMP to the GB address of the
; sprite_count byte, InitMapSprites:
;   1. Clears NPC slots 1-15 in wSpriteStateData1/2.
;   2. Reads the sprite_count and per-NPC 6/7/8-byte records from the map
;      object binary emitted by gen_map_headers.py.
;   3. Populates PICTUREID, MAPY/MAPX, MOVEMENTBYTE1/2, IMAGEBASEOFFSET,
;      ISTRAINER, and initial MOVEMENTDELAY for each NPC slot.
;   4. Calls LoadNPCSpriteTiles to copy 12 still tiles per unique sprite
;      type to the appropriate VRAM slot (imageBaseOffset-1)*192 from $8000.
;
; LoadNPCSpriteTiles loads both still tiles (→ GB_VCHARS0 slot) and walk tiles
; (→ GB_VFONT slot) from the full 24-tile sprite sheet for each unique NPC type.
;
; Build: nasm -f coff -I include/ -I . -o map_sprites.o src/engine/overworld/map_sprites.asm

bits 32

%include "gb_memmap.inc"
%include "gb_macros.inc"

extern g_tilecache_dirty
extern PrintText
extern DelayFrame
extern LoadCurrentMapView
extern MakeNPCFacePlayer
extern LoadFontTilePatterns
extern LoadPlayerSpriteGraphics
extern HandleDownArrowBlinkTiming

global InitMapSprites
global CheckNPCInteraction
global IsNPCAtTargetBlock
global w_map_text_table_ptr
global MapTextTablePointers
global CheckTrainerSight
global TrainerEncounterFlow

; ---------------------------------------------------------------------------
; Constants
; ---------------------------------------------------------------------------
NPC_TILE_BYTES  equ 12 * TILE_SIZE      ; 192 bytes = 12 tiles per sprite type
TILE_SPC        equ 0x7F               ; blank/space tile (shared with text.asm)
NPC_SLOTS_START equ 1                   ; first NPC slot (slot 0 = player)
NPC_SLOTS_MAX   equ 15                  ; max NPC slots
VRAM_SLOT_START equ 3                   ; imageBaseOffset 1=player 2=Pikachu 3+=NPCs
SPRITE_SET_SIZE equ 12                  ; max unique sprite types per map

; ---------------------------------------------------------------------------
; BSS — per-map sprite deduplication table (reset at each InitMapSprites call)
; ---------------------------------------------------------------------------
section .bss
npc_sprite_set:       resb SPRITE_SET_SIZE   ; sprite IDs in current map (0 = unused)
npc_vram_slots:       resb SPRITE_SET_SIZE   ; imageBaseOffset for each entry
w_map_text_table_ptr: resd 1                 ; flat ptr to current map's TextTable (set by EnterMap)
; TODO-GLOBAL-EVENTS: npc_beaten_flags resets per InitMapSprites (per map load).
; Replace with a persistent global wEventFlags bit array when the event system is
; implemented so trainers stay beaten across map warps.
npc_beaten_flags:     resw 1   ; bit N-1 = NPC slot N beaten; cleared in InitMapSprites
w_trainer_enc_slot:   resb 1   ; engaging trainer slot byte-offset (0xFF = none)
w_player_frozen:      resb 1   ; 1 = block player input during encounter flow

; ---------------------------------------------------------------------------
; NPC sprite tile assets and dialog text tables (section .data so flat
; DS-relative pointers in npc_sprite_data_table resolve correctly).
; ---------------------------------------------------------------------------
section .data

; npc_sprite_data_table — flat dd array indexed by sprite_id (0x00-0x52).
; Each entry is a flat pointer to the sprite's full 384-byte tile sheet
; (tiles [0-11]=still, [12-23]=walk), or 0 if that sprite_id has no asset.
; NPC_SPRITE_TABLE_SIZE equ is defined inside the include.
; Generated by tools/gen_all_assets.py — do NOT edit assets/npc_sprite_data_table.inc.
%include "assets/npc_sprite_data_table.inc"

; NPC dialog streams — per-map text tables + MapTextTablePointers dispatch.
; Generated by tools/gen_npc_dialogs.py — do NOT edit these files.
%include "assets/npc_dialogs/all_dialogs.inc"

; ---------------------------------------------------------------------------
; Code
; ---------------------------------------------------------------------------
section .text

; ---------------------------------------------------------------------------
; InitMapSprites — populate NPC sprite slots from the map's object data.
; Pret ref: engine/overworld/map_sprites.asm:InitMapSprites (outside maps path).
;
; Prerequisites: LoadMapHeader must have run; it sets W_OBJECT_DATA_PTR_TEMP to
; the GB address of the sprite_count byte in the map_object binary.
;
; All registers preserved (pushad/popad).
; ---------------------------------------------------------------------------
InitMapSprites:
    pushad

    ; --- Clear NPC slots 1-15 in wSpriteStateData1 and wSpriteStateData2 ---
    lea edi, [ebp + W_SPRITE_STATE_DATA_1 + 0x10]  ; slot 1 onward
    xor al, al
    mov ecx, NPC_SLOTS_MAX * 0x10      ; 15 * 16 = 240 bytes
    rep stosb
    lea edi, [ebp + W_SPRITE_STATE_DATA_2 + 0x10]
    mov ecx, NPC_SLOTS_MAX * 0x10
    rep stosb

    ; --- Clear per-call sprite deduplication table ---
    mov edi, npc_sprite_set
    xor al, al
    mov ecx, SPRITE_SET_SIZE * 2       ; sprite_set + vram_slots = 24 bytes
    rep stosb

    ; --- Initialize trainer encounter state (reset per map load) ---
    mov word [npc_beaten_flags], 0
    mov byte [w_trainer_enc_slot], 0xFF
    mov byte [w_player_frozen], 0

    ; --- Read sprite_count from W_OBJECT_DATA_PTR_TEMP ---
    movzx esi, word [ebp + W_OBJECT_DATA_PTR_TEMP]   ; ESI = GB addr of sprite_count
    movzx ecx, byte [ebp + esi]
    inc esi                             ; advance past sprite_count byte
    test ecx, ecx
    jz .done                            ; no NPCs on this map

    ; EBX = current slot byte offset within wSpriteStateData1/2 (slot N at N*0x10)
    ; EDX = next available imageBaseOffset (starts at VRAM_SLOT_START = 3)
    ; ESI = read pointer into GB map object binary (already past sprite_count)
    ; ECX = NPC count remaining
    mov ebx, 0x10                       ; start at slot 1 (0x10)
    mov edx, VRAM_SLOT_START            ; next_vram_slot = 3

.slot_loop:
    ; Read sprite_id byte
    movzx eax, byte [ebp + esi]
    inc esi
    mov [ebp + ebx + W_SPRITE_STATE_DATA_1 + SPRITESTATEDATA1_PICTUREID], al
    mov byte [ebp + ebx + W_SPRITE_STATE_DATA_1 + SPRITESTATEDATA1_MOVEMENTSTATUS], 0
    mov byte [ebp + ebx + W_SPRITE_STATE_DATA_1 + SPRITESTATEDATA1_FACINGDIRECTION], SPRITE_FACING_DOWN

    ; Save sprite_id (AL) and count (ECX) — FindOrAssignVramSlot may clobber ECX
    push eax
    push ecx

    ; Read mapy
    movzx eax, byte [ebp + esi]
    inc esi
    mov [ebp + ebx + W_SPRITE_STATE_DATA_2 + SPRITESTATEDATA2_MAPY], al

    ; Read mapx
    movzx eax, byte [ebp + esi]
    inc esi
    mov [ebp + ebx + W_SPRITE_STATE_DATA_2 + SPRITESTATEDATA2_MAPX], al

    ; Read mov_byte (STAY=0xFF / WALK=0xFE / scripted=<0xFE)
    movzx eax, byte [ebp + esi]
    inc esi
    mov [ebp + ebx + W_SPRITE_STATE_DATA_2 + SPRITESTATEDATA2_MOVEMENTBYTE1], al

    ; Read dir_byte (0x00=ANY / 0x01=UP_DOWN / 0x02=LEFT_RIGHT / 0xFF=NONE)
    movzx eax, byte [ebp + esi]
    inc esi
    mov [ebp + ebx + W_SPRITE_STATE_DATA_2 + SPRITESTATEDATA2_MOVEMENTBYTE2], al

    ; Set initial movement delay (30 frames before first walk attempt)
    mov byte [ebp + ebx + W_SPRITE_STATE_DATA_2 + SPRITESTATEDATA2_MOVEMENTDELAY], 30

    ; Read text_byte; check for trainer (TRAINER_FLAG = 0x40)
    movzx eax, byte [ebp + esi]
    inc esi
    xor edi, edi                        ; is_trainer = 0
    test al, TRAINER_FLAG
    jz .not_trainer
    mov edi, 1                          ; is_trainer = 1
    add esi, 2                          ; skip trainer_class + trainer_num bytes
.not_trainer:
    test al, ITEM_FLAG
    jz .not_item
    inc esi                             ; skip item_id byte (items handled by text engine, Phase 3+)
.not_item:
    ; Store text_id = text_byte & 0x3F (lower 6 bits: trainer/item flags are high bits)
    push eax
    and al, 0x3F
    mov [ebp + ebx + W_SPRITE_STATE_DATA_2 + SPRITESTATEDATA2_TEXTID], al
    pop eax
    mov [ebp + ebx + W_SPRITE_STATE_DATA_2 + SPRITESTATEDATA2_ISTRAINER], edi  ; EDI=0 or 1

    ; Assign or look up a VRAM slot for this sprite type
    pop ecx
    pop eax                             ; AL = sprite_id
    push ecx
    call FindOrAssignVramSlot           ; In: AL=sprite_id, EDX=next_slot. Out: AL=imageBaseOffset
    mov [ebp + ebx + W_SPRITE_STATE_DATA_2 + SPRITESTATEDATA2_IMAGEBASEOFFSET], al

    pop ecx
    add ebx, 0x10                       ; advance to next slot
    dec ecx
    jnz .slot_loop

.slots_done:
    call LoadNPCSpriteTiles

.done:
    popad
    ret

; ---------------------------------------------------------------------------
; FindOrAssignVramSlot — VRAM deduplication for NPC sprite types.
; Pret ref: engine/overworld/map_sprites.asm:GetSpriteImageBaseOffset (logic).
;
; In:  AL  = sprite_id
;      EDX = next available imageBaseOffset (caller-owned, updated on assign)
; Out: AL  = imageBaseOffset for this sprite_id
;      EDX = updated (incremented if a new slot was assigned)
; Clobbers: ESI, ECX
; ---------------------------------------------------------------------------
FindOrAssignVramSlot:
    push esi
    push ecx
    mov esi, 0                          ; index into npc_sprite_set
.scan:
    cmp esi, SPRITE_SET_SIZE
    jge .assign                         ; table full (shouldn't happen for ≤12 maps)
    movzx ecx, byte [npc_sprite_set + esi]
    test cl, cl
    jz .assign                          ; empty slot → sprite not seen before
    cmp cl, al
    je .found
    inc esi
    jmp .scan
.found:
    ; Return cached imageBaseOffset for this sprite_id
    movzx eax, byte [npc_vram_slots + esi]
    pop ecx
    pop esi
    ret
.assign:
    ; New sprite type — record it and assign next_vram_slot
    cmp esi, SPRITE_SET_SIZE
    jge .overflow
    mov [npc_sprite_set + esi], al
    mov [npc_vram_slots  + esi], dl
.overflow:
    mov al, dl                          ; return assigned (or last valid) slot
    inc edx                             ; next_vram_slot++
    pop ecx
    pop esi
    ret

; ---------------------------------------------------------------------------
; LoadNPCSpriteTiles — copy still tiles for each unique sprite type to VRAM.
; Pret ref: engine/overworld/map_sprites.asm:LoadMapSpriteTilePatterns /
;            ReadSpriteSheetData.
;
; Iterates npc_sprite_set; for each non-zero entry, looks up the source asset
; in NpcSpriteAssets and copies NPC_TILE_BYTES (192) bytes to:
;   [EBP + GB_VCHARS0 + (imageBaseOffset - 1) * NPC_TILE_BYTES]
;
; Sets g_tilecache_dirty = 1 after any copy.
; All registers preserved (push/pop).
; ---------------------------------------------------------------------------
LoadNPCSpriteTiles:
    push eax
    push ebx
    push ecx
    push esi
    push edi

    mov ebx, 0                          ; sprite_set index
.tile_loop:
    cmp ebx, SPRITE_SET_SIZE
    jge .done
    movzx eax, byte [npc_sprite_set + ebx]
    test al, al
    jz .done                            ; end of used entries

    ; Compute VRAM destination flat address:
    ;   edi = EBP + GB_VCHARS0 + (imageBaseOffset - 1) * NPC_TILE_BYTES
    movzx ecx, byte [npc_vram_slots + ebx]
    dec ecx                             ; (imageBaseOffset - 1)
    imul ecx, NPC_TILE_BYTES            ; * 192
    lea edi, [ebp + ecx + GB_VCHARS0]  ; flat addr in GB VRAM

    ; Look up asset source for this sprite_id (AL) via flat table.
    movzx ecx, al                        ; sprite_id as 32-bit index
    cmp ecx, NPC_SPRITE_TABLE_SIZE       ; bounds check
    jae .next_sprite
    mov esi, [npc_sprite_data_table + ecx*4]  ; pointer to 384-byte tile sheet
    test esi, esi
    jz .next_sprite                      ; no asset for this sprite_id
    ; Still tiles [0-11] → GB_VCHARS0 + (imageBaseOffset-1)*NPC_TILE_BYTES
    mov ecx, NPC_TILE_BYTES
    rep movsb
    ; Walk tiles [12-23] → GB_VFONT + (imageBaseOffset-1)*NPC_TILE_BYTES.
    ; These share GB_VFONT with the text font; LoadFontTilePatterns must be called
    ; before any PrintText call, and LoadNPCSpriteTiles after, to swap correctly.
    ; Safe for ≤6 unique NPC types per map (96 font tiles = 6 × 16-tile slots).
    movzx ecx, byte [npc_vram_slots + ebx]
    dec ecx
    imul ecx, NPC_TILE_BYTES
    lea edi, [ebp + ecx + GB_VFONT]
    mov ecx, NPC_TILE_BYTES
    rep movsb
    mov byte [g_tilecache_dirty], 1

.next_sprite:
    inc ebx
    jmp .tile_loop

.done:
    pop edi
    pop esi
    pop ecx
    pop ebx
    pop eax
    ret

; ---------------------------------------------------------------------------
; IsNPCAtTargetBlock — test if any NPC occupies the block directly in front of the player.
;
; Pret ref: home/overworld.asm:IsSpriteOrSignInFrontOfPlayer (scan loop only).
;
; Same MAPY/MAPX scan as CheckNPCInteraction.  Used by CollisionCheckOnLand to
; block the player from walking into an NPC's tile.
;
; In:  EBP = GB memory base; reads W_Y_COORD, W_X_COORD, W_SPRITE_PLAYER_FACING_DIR.
; Out: CF=1 if an NPC was found in the facing tile; CF=0 if the tile is clear.
; Preserves: all registers (push/pops EAX, EBX, ECX, ESI internally).
; ---------------------------------------------------------------------------
IsNPCAtTargetBlock:
    push eax
    push ebx
    push ecx
    push esi

    movzx ebx, byte [ebp + W_Y_COORD]
    add bl, 4                               ; BL = target MAPY (player block + MAPY bias)
    movzx ecx, byte [ebp + W_X_COORD]
    add cl, 4                               ; CL = target MAPX

    movzx eax, byte [ebp + W_SPRITE_PLAYER_FACING_DIR]
    cmp al, SPRITE_FACING_UP
    je .face_up
    cmp al, SPRITE_FACING_DOWN
    je .face_down
    cmp al, SPRITE_FACING_LEFT
    je .face_left
    inc cl                                  ; right: MAPX + 1
    jmp .scan
.face_up:
    dec bl                                  ; up:    MAPY - 1
    jmp .scan
.face_down:
    inc bl                                  ; down:  MAPY + 1
    jmp .scan
.face_left:
    dec cl                                  ; left:  MAPX - 1

.scan:
    mov esi, 0x10                           ; start at NPC slot 1
.slot_loop:
    cmp esi, 0x100
    jge .not_found
    movzx eax, byte [ebp + esi + W_SPRITE_STATE_DATA_2 + SPRITESTATEDATA2_IMAGEBASEOFFSET]
    test al, al
    jz .next_slot                           ; inactive slot
    movzx eax, byte [ebp + esi + W_SPRITE_STATE_DATA_2 + SPRITESTATEDATA2_MAPY]
    cmp al, bl
    jne .next_slot
    movzx eax, byte [ebp + esi + W_SPRITE_STATE_DATA_2 + SPRITESTATEDATA2_MAPX]
    cmp al, cl
    je .found
.next_slot:
    add esi, 0x10
    jmp .slot_loop
.found:
    pop esi
    pop ecx
    pop ebx
    pop eax
    stc
    ret
.not_found:
    pop esi
    pop ecx
    pop ebx
    pop eax
    clc
    ret

; ---------------------------------------------------------------------------
; CheckNPCInteraction — check if an NPC is one block in front of the player;
; if so, make it face the player, copy its dialog to WRAM, and run PrintText.
;
; Pret ref: home/overworld.asm:IsSpriteOrSignInFrontOfPlayer (block-coord variant).
; Called from OverworldLoop when A is pressed and W_WALK_COUNTER == 0.
;
; Detection: NPC in front iff (MAPY - 4) == W_Y_COORD + dy
;                         AND (MAPX - 4) == W_X_COORD + dx
; where (dy,dx) = (-1,0) SPRITE_FACING_UP, (+1,0) DOWN, (0,-1) LEFT, (0,+1) RIGHT.
;
; Text data from PalletTownTextTable (flat .data ptr + size) is copied to
; NPC_DIALOG_BUF in WRAM (EBP-relative). PrintText reads the TX stream from there.
;
; After PrintText (or on CHAR_DONE within PrintText), the window is already shown
; at H_WY=152 by manual_text_scroll. This function hides the window (H_WY=200),
; restores the BG, and returns AL=1 (NPC found) or AL=0 (nothing found).
;
; All registers preserved (pushad/popad). Returns AL in EAX after popad.
; ---------------------------------------------------------------------------
; Dialog-box Y constants (wTileMap rows 12-17 → GB_TILEMAP1 rows 0-5, WY=152 in 320×200).
DIALOG_TILEMAP_ROW      equ 12
DIALOG_TILEMAP_ROWS     equ 6

CheckNPCInteraction:
    pushad

    ; Compute target block coordinates from player facing direction.
    ; W_Y_COORD and W_X_COORD are raw block coords; MAPY/MAPX are raw+4.
    ; Target MAPY = W_Y_COORD + 4 + dy; target MAPX = W_X_COORD + 4 + dx.
    movzx ebx, byte [ebp + W_Y_COORD]
    add bl, 4                               ; adjust for MAPY offset (+4)
    movzx ecx, byte [ebp + W_X_COORD]
    add cl, 4                               ; adjust for MAPX offset (+4)

    movzx eax, byte [ebp + W_SPRITE_PLAYER_FACING_DIR]
    cmp al, SPRITE_FACING_UP
    je .face_up
    cmp al, SPRITE_FACING_DOWN
    je .face_down
    cmp al, SPRITE_FACING_LEFT
    je .face_left
    ; SPRITE_FACING_RIGHT (0x0C) or default
    inc cl                                  ; MAPX + 1 (block to the right)
    jmp .scan
.face_up:
    dec bl                                  ; MAPY - 1 (block to the north)
    jmp .scan
.face_down:
    inc bl                                  ; MAPY + 1 (block to the south)
    jmp .scan
.face_left:
    dec cl                                  ; MAPX - 1 (block to the west)

.scan:
    ; BL = target_mapy, CL = target_mapx
    ; Scan NPC slots 1-15 (slot 0 = player).
    mov esi, 0x10                           ; slot byte offset starts at slot 1

.slot_loop:
    cmp esi, 0x100
    jge .not_found

    ; Skip inactive slots (IMAGEBASEOFFSET == 0 means slot is unused).
    movzx eax, byte [ebp + esi + W_SPRITE_STATE_DATA_2 + SPRITESTATEDATA2_IMAGEBASEOFFSET]
    test al, al
    jz .next_slot

    ; Compare MAPY and MAPX.
    movzx eax, byte [ebp + esi + W_SPRITE_STATE_DATA_2 + SPRITESTATEDATA2_MAPY]
    cmp al, bl
    jne .next_slot
    movzx eax, byte [ebp + esi + W_SPRITE_STATE_DATA_2 + SPRITESTATEDATA2_MAPX]
    cmp al, cl
    je .found_npc
.next_slot:
    add esi, 0x10
    jmp .slot_loop

.found_npc:
    ; ── Found: NPC at target block ──────────────────────────────────────────

    ; Beaten-trainer gate: if this is a trainer whose beaten bit is set, return 0.
    cmp byte [ebp + esi + W_SPRITE_STATE_DATA_2 + SPRITESTATEDATA2_ISTRAINER], 0
    je .not_beaten_trainer
    mov edx, esi
    shr dl, 4                           ; slot number (1-15)
    dec dl                              ; bit index (0-14)
    bt word [npc_beaten_flags], dx      ; CF=1 if beaten
    jc .not_found                       ; beaten → no re-talk
.not_beaten_trainer:

    ; Set H_TILE_PLAYER_STANDING_ON so UpdateSpriteImage picks this NPC's VRAM slot.
    ; UpdateSprites leaves H_TILE_PLAYER_STANDING_ON = last-slot value after the loop;
    ; that would cause the wrong sprite tiles (e.g. Fisher's) for any earlier NPC.
    movzx eax, byte [ebp + esi + W_SPRITE_STATE_DATA_2 + SPRITESTATEDATA2_IMAGEBASEOFFSET]
    dec al
    ror al, 4                           ; (imageBaseOffset-1)*16 → high nibble for UpdateSpriteImage
    mov [ebp + H_TILE_PLAYER_STANDING_ON], al

    ; Make NPC face player (sets facing, clears BIT_FACE_PLAYER, refreshes image).
    call MakeNPCFacePlayer

    ; Freeze NPC movement during dialog.
    or byte [ebp + esi + W_SPRITE_STATE_DATA_1 + SPRITESTATEDATA1_MOVEMENTSTATUS], (1 << BIT_FACE_PLAYER)

    ; Look up text_id → text data pointer and size via per-map text table.
    movzx eax, byte [ebp + esi + W_SPRITE_STATE_DATA_2 + SPRITESTATEDATA2_TEXTID]
    lea edx, [eax * 8]                      ; 8 bytes per entry (dd ptr + dd size)
    mov ecx, [w_map_text_table_ptr]         ; flat ptr to current map's TextTable (0 if none)
    test ecx, ecx
    jz .dialog_done                         ; null table: no text for this map

    mov edi, [ecx + edx]                    ; flat DS ptr to text stream
    test edi, edi
    jz .dialog_done                         ; null entry: no text for this id

    mov ecx, [ecx + edx + 4]               ; byte count
    cmp ecx, 256
    jge .dialog_done                        ; safety: never copy more than 256 bytes

    ; Copy text stream from flat .data to NPC_DIALOG_BUF in WRAM (EBP-relative).
    mov esi, edi                            ; flat src ptr
    lea edi, [ebp + NPC_DIALOG_BUF]
    rep movsb

    ; Set W_FONT_LOADED to freeze UpdateSprites NPC movement during dialog.
    or byte [ebp + W_FONT_LOADED], (1 << BIT_FONT_LOADED)

    ; Restore font glyphs to GB_VFONT before text rendering (walk tiles share it).
    call LoadFontTilePatterns

    ; Call PrintText with ESI = EBP-relative address of NPC_DIALOG_BUF.
    mov esi, NPC_DIALOG_BUF
    call PrintText
    ; PrintText calls manual_text_scroll at CHAR_PARA/CHAR_CONT/CHAR_DONE,
    ; which shows the dialog (copies tiles to GB_TILEMAP1, H_WY=152) and waits.
    ; For text_end format (Oak): no final scroll inside PrintText; show + wait here.
    call npc_dialog_wait_impl

.dialog_done:
    ; Hide window and clear font-loaded flag.
    mov byte [ebp + H_WY], RENDER_H     ; 200 = off-screen in 320×200 viewport
    and byte [ebp + W_FONT_LOADED], ~(1 << BIT_FONT_LOADED)

    ; Reload NPC and player walk tiles into GB_VFONT (font was loaded for dialog).
    call LoadNPCSpriteTiles
    call LoadPlayerSpriteGraphics

    ; Restore the BG: rebuild wSurroundingTiles for current player position.
    call LoadCurrentMapView
    call DelayFrame

    ; Signal caller that NPC interaction occurred.
    mov dword [esp + 28], 1                 ; overwrite saved EAX slot in pushad frame
    popad
    ret

.not_found:
    xor eax, eax
    mov dword [esp + 28], 0
    popad
    ret

; ── shared helper: copy current wTileMap dialog rows to window layer, wait A/B ──
; Called by CheckNPCInteraction and TrainerEncounterFlow. Not a dot-local label so
; both callers can reach it. Preserves ECX, ESI, EDI (push/pop).
npc_dialog_wait_impl:
    ; Copy wTileMap rows 12-17 to GB_TILEMAP1 rows 0-5 (window layer source).
    push ecx
    push esi
    push edi
    mov ecx, DIALOG_TILEMAP_ROWS
    lea esi, [ebp + W_TILEMAP + DIALOG_TILEMAP_ROW * 20]
    lea edi, [ebp + GB_TILEMAP1]
.sdw_row:
    push ecx
    push edi
    mov ecx, 20                             ; 20 tiles from wTileMap
    rep movsb
    mov al, TILE_SPC
    mov ecx, 12                             ; pad cols 20-31 with space
    rep stosb
    pop edi
    pop ecx
    add edi, 32                             ; next GB_TILEMAP1 row (32 wide)
    dec ecx
    jnz .sdw_row
    mov byte [ebp + H_WY], 152             ; show window at bottom of 320×200 viewport
    mov byte [ebp + IO_WX], 87            ; WX-7=80 → center 160px dialog in 320px wide buffer
    ; Place ▼ arrow and init blink counters; save existing state to restore after.
    movzx ecx, byte [ebp + H_DOWN_ARROW_COUNT1]
    push ecx
    movzx ecx, byte [ebp + H_DOWN_ARROW_COUNT2]
    push ecx
    mov byte [ebp + H_DOWN_ARROW_COUNT1], ARROW_ON_FRAMES
    mov byte [ebp + H_DOWN_ARROW_COUNT2], 1
    mov esi, GB_TILEMAP1 + DIALOG_ARROW_TILEMAP_OFFSET
    mov byte [ebp + esi], CHAR_DOWN_ARROW
    ; Release: wait until A/B not held.
.sdw_release:
    call DelayFrame
    test byte [ebp + H_JOY_HELD], PAD_A | PAD_B
    jnz .sdw_release
    ; Press: wait for A or B; blink ▼ each frame.
.sdw_press:
    call DelayFrame
    call HandleDownArrowBlinkTiming
    test byte [ebp + H_JOY_HELD], PAD_A | PAD_B
    jz .sdw_press
    ; Clear arrow, restore blink state.
    mov byte [ebp + GB_TILEMAP1 + DIALOG_ARROW_TILEMAP_OFFSET], TILE_SPC
    pop ecx
    mov [ebp + H_DOWN_ARROW_COUNT2], cl
    pop ecx
    mov [ebp + H_DOWN_ARROW_COUNT1], cl
    pop edi
    pop esi
    pop ecx
    ret

; ---------------------------------------------------------------------------
; CheckTrainerSight — scan NPC slots 1-15 for an unbeaten trainer with the
; player in their line-of-sight (facing direction, distance ≤ 4 blocks).
;
; Sets w_trainer_enc_slot to the matching slot's byte offset if found.
; Out: CF=1 if a trainer spotted the player, CF=0 otherwise.
; All registers preserved (pushad/popad; CF set after popad).
; ---------------------------------------------------------------------------
CheckTrainerSight:
    pushad

    ; Player block coords: SPRITESTATEDATA2 slot 0 MAPY/MAPX
    movzx ebx, byte [ebp + W_SPRITE_STATE_DATA_2 + SPRITESTATEDATA2_MAPY]   ; BL = player_mapy
    movzx ecx, byte [ebp + W_SPRITE_STATE_DATA_2 + SPRITESTATEDATA2_MAPX]   ; CL = player_mapx

    mov esi, 0x10                          ; start at NPC slot 1
.cts_loop:
    cmp esi, 0x100
    jge .cts_none

    ; Skip inactive slot
    cmp byte [ebp + esi + W_SPRITE_STATE_DATA_2 + SPRITESTATEDATA2_IMAGEBASEOFFSET], 0
    je .cts_next

    ; Skip non-trainer
    cmp byte [ebp + esi + W_SPRITE_STATE_DATA_2 + SPRITESTATEDATA2_ISTRAINER], 0
    je .cts_next

    ; Skip if already beaten (bit_index = slot/0x10 - 1, i.e. 0-14)
    mov edx, esi
    shr dl, 4                              ; slot number (1-15) in DL
    dec dl                                 ; bit index (0-14)
    bt word [npc_beaten_flags], dx         ; CF = beaten bit
    jc .cts_next

    ; Load trainer position
    movzx eax, byte [ebp + esi + W_SPRITE_STATE_DATA_2 + SPRITESTATEDATA2_MAPY]  ; AL = trainer_mapy
    movzx edx, byte [ebp + esi + W_SPRITE_STATE_DATA_2 + SPRITESTATEDATA2_MAPX]  ; DL = trainer_mapx

    ; Check facing direction → sight line (BL=player_mapy, CL=player_mapx)
    movzx edi, byte [ebp + esi + W_SPRITE_STATE_DATA_1 + SPRITESTATEDATA1_FACINGDIRECTION]

    cmp edi, SPRITE_FACING_DOWN
    jne .cts_try_up
    ; DOWN: same MAPX, player south of trainer, dist ≤ 4
    cmp cl, dl                             ; player_mapx == trainer_mapx?
    jne .cts_next
    cmp bl, al                             ; player_mapy > trainer_mapy?
    jle .cts_next
    mov ah, bl
    sub ah, al                             ; dist = player_mapy - trainer_mapy
    cmp ah, 4
    ja .cts_next
    jmp .cts_found

.cts_try_up:
    cmp edi, SPRITE_FACING_UP
    jne .cts_try_left
    ; UP: same MAPX, player north of trainer, dist ≤ 4
    cmp cl, dl
    jne .cts_next
    cmp bl, al                             ; player_mapy < trainer_mapy?
    jge .cts_next
    mov ah, al
    sub ah, bl                             ; dist = trainer_mapy - player_mapy
    cmp ah, 4
    ja .cts_next
    jmp .cts_found

.cts_try_left:
    cmp edi, SPRITE_FACING_LEFT
    jne .cts_try_right
    ; LEFT: same MAPY, player west of trainer, dist ≤ 4
    cmp bl, al                             ; player_mapy == trainer_mapy?
    jne .cts_next
    cmp cl, dl                             ; player_mapx < trainer_mapx?
    jge .cts_next
    mov ah, dl
    sub ah, cl                             ; dist = trainer_mapx - player_mapx
    cmp ah, 4
    ja .cts_next
    jmp .cts_found

.cts_try_right:
    ; RIGHT: same MAPY, player east of trainer, dist ≤ 4
    cmp bl, al
    jne .cts_next
    cmp cl, dl                             ; player_mapx > trainer_mapx?
    jle .cts_next
    mov ah, cl
    sub ah, dl                             ; dist = player_mapx - trainer_mapx
    cmp ah, 4
    ja .cts_next

.cts_found:
    mov eax, esi                           ; ESI = slot offset (0x10-0xF0); AL = low byte
    mov [w_trainer_enc_slot], al           ; save slot offset (fits in a byte)
    popad
    stc
    ret

.cts_next:
    add esi, 0x10
    jmp .cts_loop

.cts_none:
    popad
    clc
    ret

; ---------------------------------------------------------------------------
; TrainerEncounterFlow — trainer encounter stub (no battle engine).
; Pret ref: home/overworld.asm:TrainerEncounter (stub).
;
; Flow: brief freeze → face trainer → show pre-battle text →
;       mark trainer beaten → clear encounter state.
;
; Reads w_trainer_enc_slot for the engaging trainer's slot offset.
; All registers preserved (pushad/popad).
; ---------------------------------------------------------------------------
TrainerEncounterFlow:
    pushad

    mov byte [w_player_frozen], 1

    ; --- Brief freeze before text (~45 frames) ---
    ; TODO: Add ! bubble over trainer's head here.
    mov ecx, 45
.tef_freeze:
    call DelayFrame
    dec ecx
    jnz .tef_freeze

    ; --- Make trainer face player and freeze NPC movement during text ---
    movzx esi, byte [w_trainer_enc_slot]   ; ESI = slot byte offset (0x10-0xF0)
    movzx eax, byte [ebp + esi + W_SPRITE_STATE_DATA_2 + SPRITESTATEDATA2_IMAGEBASEOFFSET]
    dec al
    ror al, 4
    mov [ebp + H_TILE_PLAYER_STANDING_ON], al
    call MakeNPCFacePlayer
    or byte [ebp + esi + W_SPRITE_STATE_DATA_1 + SPRITESTATEDATA1_MOVEMENTSTATUS], (1 << BIT_FACE_PLAYER)

    ; --- Look up and show pre-battle text ---
    movzx eax, byte [ebp + esi + W_SPRITE_STATE_DATA_2 + SPRITESTATEDATA2_TEXTID]
    lea edx, [eax * 8]                     ; 8 bytes per entry (dd ptr + dd size)
    mov ecx, [w_map_text_table_ptr]        ; flat ptr to current map's TextTable (0 if none)
    test ecx, ecx
    jz .tef_text_done

    mov edi, [ecx + edx]                   ; flat DS ptr to text stream
    test edi, edi
    jz .tef_text_done

    mov ecx, [ecx + edx + 4]              ; byte count
    cmp ecx, 256
    jge .tef_text_done

    ; ESI (slot offset) is consumed; save it around the rep movsb.
    push esi
    mov esi, edi                            ; text src ptr
    lea edi, [ebp + NPC_DIALOG_BUF]
    rep movsb
    pop esi                                 ; restore slot offset (not needed further, but balanced)

    or byte [ebp + W_FONT_LOADED], (1 << BIT_FONT_LOADED)
    call LoadFontTilePatterns
    mov esi, NPC_DIALOG_BUF
    call PrintText
    call npc_dialog_wait_impl

.tef_text_done:
    mov byte [ebp + H_WY], RENDER_H
    and byte [ebp + W_FONT_LOADED], ~(1 << BIT_FONT_LOADED)
    call LoadNPCSpriteTiles
    call LoadPlayerSpriteGraphics
    call LoadCurrentMapView
    call DelayFrame

    ; --- Mark trainer beaten (bit_index = slot/0x10 - 1) ---
    movzx edx, byte [w_trainer_enc_slot]
    shr dl, 4                              ; slot number (1-15)
    dec dl                                 ; bit index (0-14)
    bts word [npc_beaten_flags], dx        ; set beaten bit

    ; --- Clear encounter state ---
    mov byte [w_trainer_enc_slot], 0xFF
    mov byte [w_player_frozen], 0

    popad
    ret
