; These are all the asm constants needed to make the yellow_vc patch.

; [FPA 001 Begin]
EXPORT DEF M_CHAR EQU 'M'
EXPORT DEF E_CHAR EQU 'E'
EXPORT DEF G_CHAR EQU 'G'
EXPORT DEF A_CHAR EQU 'A'
EXPORT DEF P_CHAR EQU 'P'
EXPORT DEF X_CHAR EQU 'X'
EXPORT DEF L_CHAR EQU 'L'
EXPORT DEF S_CHAR EQU 'S'
EXPORT DEF F_CHAR EQU 'F'
EXPORT MEGA_PUNCH

; [FPA 002 Begin]
EXPORT DEF U_CHAR EQU 'U'
EXPORT DEF I_CHAR EQU 'I'
EXPORT GUILLOTINE

; [FPA 003 Begin]
EXPORT DEF K_CHAR EQU 'K'
EXPORT MEGA_KICK

; [FPA 004 Begin]
EXPORT DEF B_CHAR EQU 'B'
EXPORT DEF Z_CHAR EQU 'Z'
EXPORT BLIZZARD

; [FPA 005 Begin]
EXPORT BUBBLEBEAM

; [FPA 006 Begin]
EXPORT DEF H_CHAR EQU 'H'
EXPORT DEF Y_CHAR EQU 'Y'
EXPORT HYPER_BEAM

; [FPA 007 Begin]
EXPORT DEF T_CHAR EQU 'T'
EXPORT DEF N_CHAR EQU 'N'
EXPORT THUNDERBOLT

; [FPA 008 Begin]
EXPORT HAZE

; [FPA 009 Begin]
EXPORT DEF R_CHAR EQU 'R'
EXPORT REFLECT

; [FPA 010 Begin]
EXPORT SELFDESTRUCT

; [FPA 011 Begin]
EXPORT EXPLOSION
