; load_font.asm — expand the 1bpp text font to 2bpp and load it into vFont.
;
; Mirrors home/copy2.asm:FarCopyDataDouble, which expands 1bpp image data to
; 2bpp by writing each source byte to both bitplanes (low = high), so every
; pixel ends up color 0 (background) or 3 (foreground). With the identity BGP
; ($E4) that renders as a solid dark glyph on a light background.
;
; The font art (gfx/font/font.png, committed) is embedded as NASM data via
; assets/font_1bpp.inc (generated by tools/gen_font_inc.py using Pillow).
; With LCDC_DEFAULT ($8800 signed addressing), char code C ('A'=$80) maps to
; VRAM tile at $9000 + sext8(C)*16 = $8800 + (C-$80)*16 = vFont, so char codes
; index tiles directly and a string drops straight into a tilemap.
;
; Build: nasm -f coff -I include/ -I . -o load_font.o load_font.asm

bits 32

%include "gb_memmap.inc"
%include "gb_macros.inc"

global LoadFontTilePatterns

section .data
align 4
%include "assets/font_1bpp.inc"

section .text

; ---------------------------------------------------------------------------
; LoadFontTilePatterns — expand embedded 1bpp font into vFont ($8800) as 2bpp.
; In:  EBP = GB memory base.
; Out: all registers preserved.
; ---------------------------------------------------------------------------
LoadFontTilePatterns:
    push eax
    push ecx
    push esi
    push edi

    mov esi, font_1bpp_data
    lea edi, [ebp + GB_VFONT]
    mov ecx, FONT_1BPP_SIZE
.loop:
    lodsb
    mov ah, al
    mov [edi],     al    ; low bitplane
    mov [edi + 1], ah    ; high bitplane (duplicate → colors 0 or 3)
    add edi, 2
    dec ecx
    jnz .loop

    pop edi
    pop esi
    pop ecx
    pop eax
    ret
