CeladonMansionRoof_Script:
	call EnableAutoTextBoxDrawing
	ret

CeladonMansionRoof_TextPointers:
	def_text_pointers
	dw_const CeladonMansionRoofHouseSignText, TEXT_CELADONMANSIONROOF_HOUSE_SIGN

CeladonMansionRoofHouseSignText:
	text_far _CeladonMansionRoofHouseSignText
	text_end
