#!/usr/bin/env python3
"""Generate dos_port/assets/title_*.inc from gfx/title/ and gfx/splash/ PNGs.

Converts each source PNG to GB 2bpp tile data and writes a NASM include file.
Also converts binary .tilemap files (raw tile-index bytes) to NASM include files.

Pixel convention (same as gen_font_extra_inc.py):
  L=0   (black)       → GB color 3
  L=85  (dark gray)   → GB color 2
  L=170 (light gray)  → GB color 1
  L=255 (white/alpha) → GB color 0

Requires Pillow: pip install Pillow
Run from the repo root: python3 tools/gen_title_gfx_inc.py
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ASSETS = ROOT / "dos_port" / "assets"

TILE_W, TILE_H = 8, 8


def pixel_to_gbcolor(rgba):
    r, g, b, a = rgba
    if a < 128:
        return 0                # transparent → white (GB color 0)
    L = int(0.299 * r + 0.587 * g + 0.114 * b)
    gc = 3 - round(L / 85.0)
    return max(0, min(3, gc))


def png_to_2bpp(path: Path, expected_tiles: int | None = None) -> bytes:
    from PIL import Image
    img = Image.open(path).convert("RGBA")
    w, h = img.size
    tiles_x = w // TILE_W
    tiles_y = h // TILE_H
    num_tiles = tiles_x * tiles_y
    if expected_tiles and num_tiles != expected_tiles:
        print(f"  WARNING: expected {expected_tiles} tiles, got {num_tiles} ({w}x{h}) in {path.name}")

    data = bytearray()
    for ty in range(tiles_y):
        for tx in range(tiles_x):
            for row in range(TILE_H):
                lo = hi = 0
                for col in range(TILE_W):
                    px = img.getpixel((tx * TILE_W + col, ty * TILE_H + row))
                    gc = pixel_to_gbcolor(px)
                    bit = 0x80 >> col
                    if gc & 1:
                        lo |= bit
                    if gc & 2:
                        hi |= bit
                data.append(lo)
                data.append(hi)
    return bytes(data)


def write_2bpp_inc(dst: Path, label: str, data: bytes, comment: str = ""):
    lines = [
        f"; {dst.name} — generated by tools/gen_title_gfx_inc.py.  DO NOT EDIT BY HAND.",
    ]
    if comment:
        lines.append(f"; {comment}")
    lines += [
        "",
        f"{label}:",
    ]
    for i in range(0, len(data), 16):
        lines.append("    db " + ", ".join(f"0x{b:02X}" for b in data[i:i + 16]))
    num_tiles = len(data) // 16
    lines += [
        f"{label}_end:",
        f"{label.upper()}_SIZE equ {label}_end - {label}",
        f"{label.upper()}_TILES equ {num_tiles}",
        "",
    ]
    dst.write_text("\n".join(lines) + "\n")
    print(f"  wrote {dst} ({len(data)} bytes, {num_tiles} tiles)")


def write_tilemap_inc(dst: Path, label: str, src: Path, width: int, height: int):
    data = src.read_bytes()
    expected = width * height
    if len(data) != expected:
        print(f"  WARNING: {src.name} is {len(data)} bytes, expected {expected} ({width}×{height})")
    lines = [
        f"; {dst.name} — generated by tools/gen_title_gfx_inc.py.  DO NOT EDIT BY HAND.",
        f"; {width}×{height} tile indices for {src.stem}.",
        "",
        f"{label}:",
    ]
    for i in range(0, len(data), 16):
        lines.append("    db " + ", ".join(f"0x{b:02X}" for b in data[i:i + 16]))
    lines += [
        f"{label}_end:",
        f"{label.upper()}_WIDTH  equ {width}",
        f"{label.upper()}_HEIGHT equ {height}",
        "",
    ]
    dst.write_text("\n".join(lines) + "\n")
    print(f"  wrote {dst} ({len(data)} bytes tilemap)")


def main():
    try:
        from PIL import Image  # noqa: F401
    except ImportError:
        sys.exit("Pillow required: pip install Pillow")

    ASSETS.mkdir(parents=True, exist_ok=True)

    gfx_title  = ROOT / "gfx" / "title"
    gfx_splash = ROOT / "gfx" / "splash"

    print("Generating title screen 2bpp include files...")

    # Pokemon logo — loaded to vChars2 ($9000), tilemap is 16×7
    data = png_to_2bpp(gfx_title / "pokemon_logo.png")
    write_2bpp_inc(ASSETS / "pokemon_logo_2bpp.inc", "pokemon_logo_2bpp",
                   data, "Tiles for vChars2 ($9000); tile 0 = index $00.")

    # Pokemon logo corner tiles — 3 tiles loaded to vChars1 tile $7D ($8FD0)
    data = png_to_2bpp(gfx_title / "pokemon_logo_corner.png")
    write_2bpp_inc(ASSETS / "pokemon_logo_corner_2bpp.inc", "pokemon_logo_corner_2bpp",
                   data, "3 corner tiles loaded to vChars1 tile $7D.")

    # Pikachu BG tiles — loaded to vChars1 ($8800), tile index $80 = first tile
    data = png_to_2bpp(gfx_title / "pikachu_bg.png")
    write_2bpp_inc(ASSETS / "pikachu_bg_2bpp.inc", "pikachu_bg_2bpp",
                   data, "BG tiles loaded to vChars1 ($8800); tile $80 = first.")

    # Pikachu OBJ tiles — loaded to vChars1 tile $70 ($8F00)
    data = png_to_2bpp(gfx_title / "pikachu_ob.png")
    write_2bpp_inc(ASSETS / "pikachu_ob_2bpp.inc", "pikachu_ob_2bpp",
                   data, "OBJ sprite tiles loaded to vChars1 tile $70 ($8F00).")

    # Nintendo copyright tiles — 5 tiles loaded to vChars2 tile $60 ($9600)
    data = png_to_2bpp(gfx_splash / "copyright.png")
    write_2bpp_inc(ASSETS / "title_copyright_2bpp.inc", "title_copyright_2bpp",
                   data, "Nintendo copyright tiles loaded to vChars2 tile $60.")

    # GameFreak inc. logo — 9 tiles loaded to vChars2 tile $65 ($9650)
    data = png_to_2bpp(gfx_title / "gamefreak_inc.png")
    write_2bpp_inc(ASSETS / "gamefreak_inc_2bpp.inc", "gamefreak_inc_2bpp",
                   data, "GameFreak inc logo tiles loaded to vChars2 tile $65.")

    # Nine tile — 1 tile loaded to vChars2 tile $6E ($96E0)
    data = png_to_2bpp(gfx_title / "nine.png")
    write_2bpp_inc(ASSETS / "nine_2bpp.inc", "nine_2bpp",
                   data, "Nine tile loaded to vChars2 tile $6E.")

    print("Generating title screen tilemap include files...")

    write_tilemap_inc(ASSETS / "pokemon_logo_tilemap.inc", "pokemon_logo_tilemap",
                      gfx_title / "pokemon_logo.tilemap", 16, 7)

    write_tilemap_inc(ASSETS / "pikachu_tilemap.inc", "pikachu_tilemap",
                      gfx_title / "pikachu.tilemap", 12, 9)

    write_tilemap_inc(ASSETS / "pika_bubble_tilemap.inc", "pika_bubble_tilemap",
                      gfx_title / "pika_bubble.tilemap", 7, 4)

    print("Done.")


if __name__ == "__main__":
    main()
