#!/usr/bin/env python3
"""Generate dos_port/assets/map_headers.inc from hardcoded constants.

Generates relocated map headers, connection structs, and object data stubs
for Pallet Town, Route 1, and Route 21.
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ASSETS = ROOT / "dos_port" / "assets"

def get_connection(direction, conn_map_id, offset, cur_width, cur_height, conn_width, conn_height):
    _src = 0
    _tgt = offset + 3
    if _tgt < 2:
        _src = -_tgt
        _tgt = 0

    if direction == "NORTH":
        _blk = conn_width * (conn_height - 3) + _src
        _map = _tgt
        # Subtract one block row vs pret: pret carries accumulated H_SCY into the
        # new map, so its _win was designed for H_SCY≠0.  Our port resets H_SCY=0
        # and calls CopyMapViewToVRAM, placing the player (OAM Y=96→screen Y=80,
        # tile row 10) at wSurroundingTiles block row 3 from view_start (Y_BC=1
        # adds 2 tile rows → tile 12 → block 3).  So view_start = player_wOW_row
        # − 3, which is one stride less than pret's formula.
        _win = (conn_width + 6) * (conn_height - 1) + 1
        _y = conn_height * 2 - 1
        _x = offset * -2
        _len = cur_width + 3 - offset
        if _len > conn_width: _len = conn_width
        
    elif direction == "SOUTH":
        _blk = _src
        _map = (cur_width + 6) * (cur_height + 3) + _tgt
        _win = conn_width + 7
        _y = 0
        _x = offset * -2
        _len = cur_width + 3 - offset
        if _len > conn_width: _len = conn_width
        
    elif direction == "WEST":
        _blk = conn_width * _src + conn_width - 3
        _map = (cur_width + 6) * _tgt
        _win = (conn_width + 6) * 2 - 6
        _y = offset * -2
        _x = conn_width * 2 - 1
        _len = cur_height + 3 - offset
        if _len > conn_height: _len = conn_height
        
    elif direction == "EAST":
        _blk = conn_width * _src
        _map = (cur_width + 6) * _tgt + cur_width + 3
        _win = conn_width + 7
        _y = offset * -2
        _x = 0
        _len = cur_height + 3 - offset
        if _len > conn_height: _len = conn_height
        
    strip_length = _len - _src
    
    return {
        "conn_map_id": conn_map_id,
        "blk": _blk,
        "map": _map,
        "win": _win,
        "y": _y,
        "x": _x,
        "len": strip_length,
        "conn_width": conn_width
    }

def main():
    ASSETS.mkdir(parents=True, exist_ok=True)
    out_path = ASSETS / "map_headers.inc"
    
    lines = [
        "; map_headers.inc — generated by tools/gen_map_headers.py. DO NOT EDIT BY HAND.",
        "",
        "OW_TILESET_HDR_GBADDR equ 0x5400",
        "OW_MAP_HEADERS_GBADDR equ 0x540C",
        "",
        "map_headers_data:"
    ]
    
    # 1. OVERWORLD tileset header (12 bytes)
    lines.extend([
        "tileset_header_OVERWORLD:",
        "    db 0x01 ; bank",
        "    dw OW_BLOCKS_GBADDR ; blocks",
        "    dw OW_GFX_GBADDR ; gfx",
        "    dw OW_COLL_GBADDR ; collision",
        "    db 0xFF, 0xFF, 0xFF ; counters",
        "    db 0x52 ; grass tile",
        "    db 0x02 ; animations",
        ""
    ])
    
    # Map definitions
    W_OVERWORLD_MAP = 0xE580
    
    maps = {
        "PALLET_TOWN": {"id": 0x00, "width": 10, "height": 9, "blk_addr": 0x4E00, "border": 0x0B, "warps": 3, "signs": 4, "sprites": 3},
        "ROUTE_1":     {"id": 0x0C, "width": 10, "height": 18, "blk_addr": 0x5000, "border": 0x0B, "warps": 0, "signs": 1, "sprites": 2},
        "ROUTE_21":    {"id": 0x20, "width": 10, "height": 45, "blk_addr": 0x5200, "border": 0x43, "warps": 0, "signs": 0, "sprites": 9},
    }
    
    # connections: map -> list of (direction, target_name, offset)
    conns = {
        "PALLET_TOWN": [("NORTH", "ROUTE_1", 0), ("SOUTH", "ROUTE_21", 0)],
        "ROUTE_1":     [("SOUTH", "PALLET_TOWN", 0)], # Omit NORTH Viridian
        "ROUTE_21":    [("NORTH", "PALLET_TOWN", 0)]  # Omit SOUTH Cinnabar
    }
    
    conn_bits = {"NORTH": 0x08, "SOUTH": 0x04, "WEST": 0x02, "EAST": 0x01}
    
    current_addr = 0x540C
    
    map_addrs = {}
    
    # Generate headers and objects
    for name, m in maps.items():
        # Header
        map_addrs[name] = current_addr
        
        my_conns = conns.get(name, [])
        conn_flags = sum(conn_bits[d] for d, _, _ in my_conns)
        
        lines.append(f"OW_MAP_HDR_{name} equ 0x{current_addr:04X}")
        lines.append(f"map_header_{name}:")
        lines.append(f"    db 0x00 ; tileset OVERWORLD")
        lines.append(f"    db {m['height']}, {m['width']} ; height, width")
        lines.append(f"    dw 0x{m['blk_addr']:04X} ; blocks_ptr")
        lines.append(f"    dw 0x0000 ; text_ptr")
        lines.append(f"    dw 0x0000 ; script_ptr")
        lines.append(f"    db 0x{conn_flags:02X} ; connections")
        current_addr += 10
        
        # Output connections in N,S,W,E order.
        for check_d in ["NORTH", "SOUTH", "WEST", "EAST"]:
            for d, tname, offset in my_conns:
                if d == check_d:
                    t = maps[tname]
                    c = get_connection(d, t["id"], offset, m["width"], m["height"], t["width"], t["height"])
                    
                    strip_src = t["blk_addr"] + c["blk"]
                    strip_dest = W_OVERWORLD_MAP + c["map"]
                    view_ptr = W_OVERWORLD_MAP + c["win"]
                    
                    lines.append(f"    ; {d} connection to {tname}")
                    lines.append(f"    db 0x{c['conn_map_id']:02X} ; map id")
                    lines.append(f"    dw 0x{strip_src:04X} ; strip src")
                    lines.append(f"    dw 0x{strip_dest:04X} ; strip dest")
                    lines.append(f"    db {c['len']} ; strip length")
                    lines.append(f"    db {c['conn_width']} ; connected map width")
                    lines.append(f"    db {c['y']}, {c['x']} ; Y, X align")
                    lines.append(f"    dw 0x{view_ptr:04X} ; view ptr")
                    current_addr += 11
        
        lines.append(f"    dw 0x{current_addr + 2:04X} ; object_data_ptr")
        current_addr += 2
        
        # Object data
        lines.append(f"map_object_{name}:")
        lines.append(f"    db 0x{m['border']:02X} ; border block")
        lines.append(f"    db {m['warps']} ; warp count")
        current_addr += 2
        if m['warps'] > 0:
            lines.append(f"    times {m['warps'] * 4} db 0 ; warp stubs")
            current_addr += m['warps'] * 4
        lines.append(f"    db {m['signs']} ; sign count")
        current_addr += 1
        if m['signs'] > 0:
            lines.append(f"    times {m['signs'] * 3} db 0 ; sign stubs")
            current_addr += m['signs'] * 3
        lines.append(f"    db {m['sprites']} ; sprite count")
        current_addr += 1
        # No sprite data
        lines.append("")
        
    # MapHeaderPointers table
    max_id = max(m["id"] for m in maps.values())
    lines.append("MapHeaderPointers:")
    for i in range(max_id + 1):
        found = None
        for name, m in maps.items():
            if m["id"] == i:
                found = name
                break
        if found:
            lines.append(f"    dw OW_MAP_HDR_{found}")
        else:
            lines.append(f"    dw 0x0000 ; map {i} unimplemented")
            
    lines.append("")
    lines.append(f"MAP_HEADERS_DATA_SIZE equ $ - map_headers_data")
    lines.append("")
    
    out_path.write_text("\n".join(lines) + "\n")
    print(f"Wrote {out_path}")

if __name__ == '__main__':
    main()
