#!/usr/bin/env python3
"""Generate dos_port/assets/map_headers.inc from hardcoded constants.

Generates relocated map headers, connection structs, and object data stubs
for Pallet Town, Route 1, and Route 21.
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ASSETS = ROOT / "dos_port" / "assets"

def get_connection(direction, conn_map_id, offset, cur_width, cur_height, conn_width, conn_height):
    BORDER = 6
    stride = conn_width + 2 * BORDER
    
    _src = 0
    _tgt = offset + BORDER
    if _tgt < 2:
        _src = -_tgt
        _tgt = 0

    if direction == "NORTH":
        _blk = conn_width * (conn_height - BORDER) + _src
        _map = _tgt
        # NORTH always enters with wYBlockCoord=1 (wYCoord=conn_height*2-1 is odd),
        # so LoadCurrentMapView skips 2 tile rows from wSurroundingTiles.  Player
        # must land at view block row 4 (wSurroundingTiles tile 16 → with YBC=1
        # skip 2 → wTileMap row 16; feet at tile 19 → wTileMap row 17 = PLAYER_STANDING_ROW).
        # player_wOW_row = BORDER + conn_height - 1; view_start = player_wOW_row - 4.
        view_start_row = conn_height + BORDER - 5
        view_start_col = BORDER - 6
        _win = view_start_row * stride + view_start_col
        _y = conn_height * 2 - 1
        _x = offset * -2
        _len = cur_width + BORDER - offset
        if _len > conn_width: _len = conn_width
        
    elif direction == "SOUTH":
        _blk = _src
        _map = (cur_width + 2 * BORDER) * (cur_height + BORDER) + _tgt
        view_start_row = BORDER - 4
        view_start_col = BORDER - 6
        _win = view_start_row * stride + view_start_col
        _y = 0
        _x = offset * -2
        _len = cur_width + BORDER - offset
        if _len > conn_width: _len = conn_width
        
    elif direction == "WEST":
        _blk = conn_width * _src + conn_width - BORDER
        _map = (cur_width + 2 * BORDER) * _tgt
        view_start_row = BORDER - 4
        # WEST always enters with wXBlockCoord=1 (wXCoord=conn_width*2-1 is odd),
        # so LoadCurrentMapView skips 2 tile cols.  Player must land at view block
        # col 6 (wSurroundingTiles col 24+2=26 → skip 2 → wTileMap col 24 = PLAYER_STANDING_COL).
        # player_wOW_col = BORDER + conn_width - 1; view_start_col = player_wOW_col - 6.
        view_start_col = conn_width + BORDER - 7
        _win = view_start_row * stride + view_start_col
        _y = offset * -2
        _x = conn_width * 2 - 1
        _len = cur_height + BORDER - offset
        if _len > conn_height: _len = conn_height
        
    elif direction == "EAST":
        _blk = conn_width * _src
        _map = (cur_width + 2 * BORDER) * _tgt + cur_width + BORDER
        view_start_row = BORDER - 4
        view_start_col = BORDER - 6
        _win = view_start_row * stride + view_start_col
        _y = offset * -2
        _x = 0
        _len = cur_height + BORDER - offset
        if _len > conn_height: _len = conn_height
        
    strip_length = _len - _src
    
    return {
        "conn_map_id": conn_map_id,
        "blk": _blk,
        "map": _map,
        "win": _win,
        "y": _y,
        "x": _x,
        "len": strip_length,
        "conn_width": conn_width
    }

def main():
    ASSETS.mkdir(parents=True, exist_ok=True)
    out_path = ASSETS / "map_headers.inc"
    
    lines = [
        "; map_headers.inc — generated by tools/gen_map_headers.py. DO NOT EDIT BY HAND.",
        "",
        "OW_TILESET_HDR_GBADDR equ 0x5400",
        "OW_MAP_HEADERS_GBADDR equ 0x540C",
        "",
        "map_headers_data:"
    ]
    
    # 1. OVERWORLD tileset header (12 bytes)
    lines.extend([
        "tileset_header_OVERWORLD:",
        "    db 0x01 ; bank",
        "    dw OW_BLOCKS_GBADDR ; blocks",
        "    dw OW_GFX_GBADDR ; gfx",
        "    dw OW_COLL_GBADDR ; collision",
        "    db 0xFF, 0xFF, 0xFF ; counters",
        "    db 0x52 ; grass tile",
        "    db 0x02 ; animations",
        ""
    ])
    
    # Map definitions
    W_OVERWORLD_MAP = 0xE800
    
    maps = {
        # id, width, height, blk_addr, border, warps, signs, sprites
        # (door warps left as stubs throughout; warps/signs/sprites from pret but unwired)
        "PALLET_TOWN":    {"id": 0x00, "width": 10, "height":  9, "blk_addr": 0x4E00, "border": 0x0B, "warps": 3, "signs": 4, "sprites": 0},
        "VIRIDIAN_CITY":  {"id": 0x01, "width": 20, "height": 18, "blk_addr": 0x1000, "border": 0x0F, "warps": 0, "signs": 0, "sprites": 0},
        "PEWTER_CITY":    {"id": 0x02, "width": 20, "height": 18, "blk_addr": 0x1168, "border": 0x0A, "warps": 0, "signs": 0, "sprites": 0},
        "CERULEAN_CITY":  {"id": 0x03, "width": 20, "height": 18, "blk_addr": 0x12D0, "border": 0x0A, "warps": 0, "signs": 0, "sprites": 0},
        "LAVENDER_TOWN":  {"id": 0x04, "width": 10, "height":  9, "blk_addr": 0x1438, "border": 0x2C, "warps": 0, "signs": 0, "sprites": 0},
        "VERMILION_CITY": {"id": 0x05, "width": 20, "height": 18, "blk_addr": 0x1492, "border": 0x43, "warps": 0, "signs": 0, "sprites": 0},
        "CELADON_CITY":   {"id": 0x06, "width": 25, "height": 18, "blk_addr": 0x15FA, "border": 0x0F, "warps": 0, "signs": 0, "sprites": 0},
        "FUCHSIA_CITY":   {"id": 0x07, "width": 20, "height": 18, "blk_addr": 0x17BC, "border": 0x0F, "warps": 0, "signs": 0, "sprites": 0},
        "CINNABAR_ISLAND":{"id": 0x08, "width": 10, "height":  9, "blk_addr": 0x1924, "border": 0x43, "warps": 0, "signs": 0, "sprites": 0},
        "SAFFRON_CITY":   {"id": 0x0A, "width": 20, "height": 18, "blk_addr": 0x197E, "border": 0x0F, "warps": 0, "signs": 0, "sprites": 0},
        "ROUTE_1":        {"id": 0x0C, "width": 10, "height": 18, "blk_addr": 0x5000, "border": 0x0B, "warps": 0, "signs": 1, "sprites": 0},
        "ROUTE_2":        {"id": 0x0D, "width": 10, "height": 36, "blk_addr": 0x1AE6, "border": 0x0F, "warps": 0, "signs": 0, "sprites": 0},
        "ROUTE_3":        {"id": 0x0E, "width": 35, "height":  9, "blk_addr": 0x1C4E, "border": 0x2C, "warps": 0, "signs": 0, "sprites": 0},
        "ROUTE_4":        {"id": 0x0F, "width": 45, "height":  9, "blk_addr": 0x1D89, "border": 0x2C, "warps": 0, "signs": 0, "sprites": 0},
        "ROUTE_5":        {"id": 0x10, "width": 10, "height": 18, "blk_addr": 0x1F1E, "border": 0x0A, "warps": 0, "signs": 0, "sprites": 0},
        "ROUTE_6":        {"id": 0x11, "width": 10, "height": 18, "blk_addr": 0x1FD2, "border": 0x0F, "warps": 0, "signs": 0, "sprites": 0},
        "ROUTE_7":        {"id": 0x12, "width": 10, "height":  9, "blk_addr": 0x2086, "border": 0x0F, "warps": 0, "signs": 0, "sprites": 0},
        "ROUTE_8":        {"id": 0x13, "width": 30, "height":  9, "blk_addr": 0x20E0, "border": 0x2C, "warps": 0, "signs": 0, "sprites": 0},
        "ROUTE_9":        {"id": 0x14, "width": 30, "height":  9, "blk_addr": 0x21EE, "border": 0x2C, "warps": 0, "signs": 0, "sprites": 0},
        "ROUTE_10":       {"id": 0x15, "width": 10, "height": 36, "blk_addr": 0x22FC, "border": 0x2C, "warps": 0, "signs": 0, "sprites": 0},
        "ROUTE_11":       {"id": 0x16, "width": 30, "height":  9, "blk_addr": 0x2464, "border": 0x0F, "warps": 0, "signs": 0, "sprites": 0},
        "ROUTE_12":       {"id": 0x17, "width": 10, "height": 54, "blk_addr": 0x2572, "border": 0x43, "warps": 0, "signs": 0, "sprites": 0},
        "ROUTE_13":       {"id": 0x18, "width": 30, "height":  9, "blk_addr": 0x278E, "border": 0x43, "warps": 0, "signs": 0, "sprites": 0},
        "ROUTE_14":       {"id": 0x19, "width": 10, "height": 27, "blk_addr": 0x289C, "border": 0x43, "warps": 0, "signs": 0, "sprites": 0},
        "ROUTE_15":       {"id": 0x1A, "width": 30, "height":  9, "blk_addr": 0x29AA, "border": 0x43, "warps": 0, "signs": 0, "sprites": 0},
        "ROUTE_16":       {"id": 0x1B, "width": 20, "height":  9, "blk_addr": 0x2AB8, "border": 0x0F, "warps": 0, "signs": 0, "sprites": 0},
        "ROUTE_17":       {"id": 0x1C, "width": 10, "height": 72, "blk_addr": 0x2B6C, "border": 0x43, "warps": 0, "signs": 0, "sprites": 0},
        "ROUTE_18":       {"id": 0x1D, "width": 25, "height":  9, "blk_addr": 0x2E3C, "border": 0x43, "warps": 0, "signs": 0, "sprites": 0},
        "ROUTE_19":       {"id": 0x1E, "width": 10, "height": 27, "blk_addr": 0x2F1D, "border": 0x43, "warps": 0, "signs": 0, "sprites": 0},
        "ROUTE_20":       {"id": 0x1F, "width": 50, "height":  9, "blk_addr": 0x302B, "border": 0x43, "warps": 0, "signs": 0, "sprites": 0},
        "ROUTE_21":       {"id": 0x20, "width": 10, "height": 45, "blk_addr": 0x5200, "border": 0x43, "warps": 0, "signs": 0, "sprites": 0},
        "ROUTE_22":       {"id": 0x21, "width": 20, "height":  9, "blk_addr": 0x31ED, "border": 0x2C, "warps": 0, "signs": 0, "sprites": 0},
        "ROUTE_24":       {"id": 0x23, "width": 10, "height": 18, "blk_addr": 0x32A1, "border": 0x2C, "warps": 0, "signs": 0, "sprites": 0},
        "ROUTE_25":       {"id": 0x24, "width": 30, "height":  9, "blk_addr": 0x3355, "border": 0x2C, "warps": 0, "signs": 0, "sprites": 0},
    }

    # connections: map -> list of (direction, target_name, offset)
    # Offsets from pret headers. Connections to non-overworld maps omitted.
    conns = {
        "PALLET_TOWN":    [("NORTH", "ROUTE_1",        0),
                           ("SOUTH", "ROUTE_21",       0)],
        "VIRIDIAN_CITY":  [("NORTH", "ROUTE_2",        5),
                           ("SOUTH", "ROUTE_1",        5),
                           ("WEST",  "ROUTE_22",       4)],
        "PEWTER_CITY":    [("SOUTH", "ROUTE_2",        5),
                           ("EAST",  "ROUTE_3",        4)],
        "CERULEAN_CITY":  [("NORTH", "ROUTE_24",       5),
                           ("SOUTH", "ROUTE_5",        5),
                           ("WEST",  "ROUTE_4",        4),
                           ("EAST",  "ROUTE_9",        4)],
        "LAVENDER_TOWN":  [("NORTH", "ROUTE_10",       0),
                           ("SOUTH", "ROUTE_12",       0),
                           ("WEST",  "ROUTE_8",        0)],
        "VERMILION_CITY": [("NORTH", "ROUTE_6",        5),
                           ("EAST",  "ROUTE_11",       4)],
        "CELADON_CITY":   [("WEST",  "ROUTE_16",       4),
                           ("EAST",  "ROUTE_7",        4)],
        "FUCHSIA_CITY":   [("SOUTH", "ROUTE_19",       5),
                           ("WEST",  "ROUTE_18",       4),
                           ("EAST",  "ROUTE_15",       4)],
        "CINNABAR_ISLAND":[("NORTH", "ROUTE_21",       0),
                           ("EAST",  "ROUTE_20",       0)],
        "SAFFRON_CITY":   [("NORTH", "ROUTE_5",        5),
                           ("SOUTH", "ROUTE_6",        5),
                           ("WEST",  "ROUTE_7",        4),
                           ("EAST",  "ROUTE_8",        4)],
        "ROUTE_1":        [("NORTH", "VIRIDIAN_CITY",  5),
                           ("SOUTH", "PALLET_TOWN",    0)],
        "ROUTE_2":        [("NORTH", "PEWTER_CITY",   -5),
                           ("SOUTH", "VIRIDIAN_CITY", -5)],
        "ROUTE_3":        [("NORTH", "ROUTE_4",       25),
                           ("WEST",  "PEWTER_CITY",   -4)],
        "ROUTE_4":        [("SOUTH", "ROUTE_3",      -25),
                           ("EAST",  "CERULEAN_CITY", -4)],
        "ROUTE_5":        [("NORTH", "CERULEAN_CITY", -5),
                           ("SOUTH", "SAFFRON_CITY",  -5)],
        "ROUTE_6":        [("NORTH", "SAFFRON_CITY",  -5),
                           ("SOUTH", "VERMILION_CITY",-5)],
        "ROUTE_7":        [("WEST",  "CELADON_CITY",  -4),
                           ("EAST",  "SAFFRON_CITY",  -4)],
        "ROUTE_8":        [("WEST",  "SAFFRON_CITY",  -4),
                           ("EAST",  "LAVENDER_TOWN",  0)],
        "ROUTE_9":        [("WEST",  "CERULEAN_CITY", -4),
                           ("EAST",  "ROUTE_10",       0)],
        "ROUTE_10":       [("SOUTH", "LAVENDER_TOWN",  0),
                           ("WEST",  "ROUTE_9",        0)],
        "ROUTE_11":       [("WEST",  "VERMILION_CITY",-4),
                           ("EAST",  "ROUTE_12",     -27)],
        "ROUTE_12":       [("NORTH", "LAVENDER_TOWN",  0),
                           ("SOUTH", "ROUTE_13",     -20),
                           ("WEST",  "ROUTE_11",      27)],
        "ROUTE_13":       [("NORTH", "ROUTE_12",      20),
                           ("WEST",  "ROUTE_14",       0)],
        "ROUTE_14":       [("WEST",  "ROUTE_15",      18),
                           ("EAST",  "ROUTE_13",       0)],
        "ROUTE_15":       [("WEST",  "FUCHSIA_CITY",  -4),
                           ("EAST",  "ROUTE_14",     -18)],
        "ROUTE_16":       [("SOUTH", "ROUTE_17",       0),
                           ("EAST",  "CELADON_CITY",  -4)],
        "ROUTE_17":       [("NORTH", "ROUTE_16",       0),
                           ("SOUTH", "ROUTE_18",       0)],
        "ROUTE_18":       [("NORTH", "ROUTE_17",       0),
                           ("EAST",  "FUCHSIA_CITY",  -4)],
        "ROUTE_19":       [("NORTH", "FUCHSIA_CITY",  -5),
                           ("WEST",  "ROUTE_20",      18)],
        "ROUTE_20":       [("WEST",  "CINNABAR_ISLAND", 0),
                           ("EAST",  "ROUTE_19",     -18)],
        "ROUTE_21":       [("NORTH", "PALLET_TOWN",    0),
                           ("SOUTH", "CINNABAR_ISLAND",0)],
        "ROUTE_22":       [("EAST",  "VIRIDIAN_CITY", -4)],  # Omit NORTH Route23 (non-overworld)
        "ROUTE_24":       [("SOUTH", "CERULEAN_CITY", -5),
                           ("EAST",  "ROUTE_25",       0)],
        "ROUTE_25":       [("WEST",  "ROUTE_24",       0)],
    }
    
    conn_bits = {"NORTH": 0x08, "SOUTH": 0x04, "WEST": 0x02, "EAST": 0x01}
    
    current_addr = 0x540C
    
    map_addrs = {}
    
    # Generate headers and objects
    for name, m in maps.items():
        # Header
        map_addrs[name] = current_addr
        
        my_conns = conns.get(name, [])
        conn_flags = sum(conn_bits[d] for d, _, _ in my_conns)
        
        lines.append(f"OW_MAP_HDR_{name} equ 0x{current_addr:04X}")
        lines.append(f"map_header_{name}:")
        lines.append(f"    db 0x00 ; tileset OVERWORLD")
        lines.append(f"    db {m['height']}, {m['width']} ; height, width")
        lines.append(f"    dw 0x{m['blk_addr']:04X} ; blocks_ptr")
        lines.append(f"    dw 0x0000 ; text_ptr")
        lines.append(f"    dw 0x0000 ; script_ptr")
        lines.append(f"    db 0x{conn_flags:02X} ; connections")
        current_addr += 10
        
        # Output connections in N,S,W,E order.
        for check_d in ["NORTH", "SOUTH", "WEST", "EAST"]:
            for d, tname, offset in my_conns:
                if d == check_d:
                    t = maps[tname]
                    c = get_connection(d, t["id"], offset, m["width"], m["height"], t["width"], t["height"])
                    
                    strip_src = t["blk_addr"] + c["blk"]
                    strip_dest = W_OVERWORLD_MAP + c["map"]
                    view_ptr = W_OVERWORLD_MAP + c["win"]
                    
                    lines.append(f"    ; {d} connection to {tname}")
                    lines.append(f"    db 0x{c['conn_map_id']:02X} ; map id")
                    lines.append(f"    dw 0x{strip_src:04X} ; strip src")
                    lines.append(f"    dw 0x{strip_dest:04X} ; strip dest")
                    lines.append(f"    db {c['len']} ; strip length")
                    lines.append(f"    db {c['conn_width']} ; connected map width")
                    lines.append(f"    db {c['y']}, {c['x']} ; Y, X align")
                    lines.append(f"    dw 0x{view_ptr:04X} ; view ptr")
                    current_addr += 11
        
        lines.append(f"    dw 0x{current_addr + 2:04X} ; object_data_ptr")
        current_addr += 2
        
        # Object data
        lines.append(f"map_object_{name}:")
        lines.append(f"    db 0x{m['border']:02X} ; border block")
        lines.append(f"    db {m['warps']} ; warp count")
        current_addr += 2
        if m['warps'] > 0:
            lines.append(f"    times {m['warps'] * 4} db 0 ; warp stubs")
            current_addr += m['warps'] * 4
        lines.append(f"    db {m['signs']} ; sign count")
        current_addr += 1
        if m['signs'] > 0:
            lines.append(f"    times {m['signs'] * 3} db 0 ; sign stubs")
            current_addr += m['signs'] * 3
        lines.append(f"    db {m['sprites']} ; sprite count")
        current_addr += 1
        # No sprite data
        lines.append("")
        
    # MapHeaderPointers table
    max_id = max(m["id"] for m in maps.values())
    lines.append("MapHeaderPointers:")
    for i in range(max_id + 1):
        found = None
        for name, m in maps.items():
            if m["id"] == i:
                found = name
                break
        if found:
            lines.append(f"    dw OW_MAP_HDR_{found}")
        else:
            lines.append(f"    dw 0x0000 ; map {i} unimplemented")
            
    lines.append("")
    lines.append(f"MAP_HEADERS_DATA_SIZE equ $ - map_headers_data")
    lines.append("")
    
    out_path.write_text("\n".join(lines) + "\n")
    print(f"Wrote {out_path}")

if __name__ == '__main__':
    main()
