#!/usr/bin/env python3
"""Generate dos_port/assets/overworld_*.inc from repo binary assets.

Reads three binary files and writes NASM include files following the same
db-hex format used by gen_title_gfx_inc.py.

  overworld.2bpp   — built by 'make' in repo root (rgbgfx --trim-whitespace)
  overworld.bst    — checked-in blockset (128 blocks × 16 tile-IDs each)
  PalletTown.blk   — checked-in map (10×9 = 90 block IDs)

Run from the repo root:
    python3 tools/gen_overworld_assets.py

If overworld.2bpp is missing, run 'make' in the repo root first.
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ASSETS = ROOT / "dos_port" / "assets"


def write_inc(dst: Path, label: str, data: bytes, comment: str = ""):
    lines = [
        f"; {dst.name} — generated by tools/gen_overworld_assets.py.  DO NOT EDIT BY HAND.",
    ]
    if comment:
        lines.append(f"; {comment}")
    lines += ["", f"{label}:"]
    for i in range(0, len(data), 16):
        lines.append("    db " + ", ".join(f"0x{b:02X}" for b in data[i : i + 16]))
    size = len(data)
    lines += [
        f"{label}_end:",
        f"{label.upper()}_SIZE equ {label}_end - {label}",
        "",
    ]
    dst.write_text("\n".join(lines) + "\n")
    print(f"  wrote {dst} ({size} bytes)")


def parse_coll_list(coll_src: Path, label: str) -> bytes:
    """Extract one `<label>_Coll:: coll_tiles ...` row from collision_tile_ids.asm.

    The pret macro emits the listed tile IDs followed by a $FF terminator, so the
    returned bytes are the passable-tile list IsTilePassable scans (ending in $FF).
    Labels may stack (several share one coll_tiles line); we take the first
    coll_tiles line at or after the requested label.
    """
    want = f"{label}_Coll::"
    lines = coll_src.read_text().splitlines()
    seen = False
    for line in lines:
        s = line.strip()
        if s.startswith(want):
            seen = True
        if seen and "coll_tiles" in s:
            args = s.split("coll_tiles", 1)[1]
            ids = [int(tok.strip().replace("$", "0x"), 16)
                   for tok in args.split(",") if tok.strip()]
            return bytes(ids) + b"\xff"
    raise SystemExit(f"ERROR: {want} not found in {coll_src}")


def main():
    gfx_src    = ROOT / "gfx" / "tilesets" / "overworld.2bpp"
    blocks_src = ROOT / "gfx" / "blocksets" / "overworld.bst"
    map_src    = ROOT / "maps" / "PalletTown.blk"
    coll_src   = ROOT / "data" / "tilesets" / "collision_tile_ids.asm"
    player_src = ROOT / "gfx" / "sprites" / "red.2bpp"

    if not gfx_src.exists():
        print(f"ERROR: {gfx_src} not found.", file=sys.stderr)
        print("Run 'make' in the repo root first to build .2bpp files.", file=sys.stderr)
        sys.exit(1)

    ASSETS.mkdir(parents=True, exist_ok=True)

    write_inc(
        ASSETS / "overworld_gfx.inc",
        "overworld_gfx",
        gfx_src.read_bytes(),
        "Overworld tileset 2bpp data → [EBP+OW_GFX_GBADDR] → vTileset ($9000).",
    )
    write_inc(
        ASSETS / "overworld_blocks.inc",
        "overworld_blocks",
        blocks_src.read_bytes(),
        "Overworld blockset: 128 blocks × 16 tile-IDs each → [EBP+OW_BLOCKS_GBADDR].",
    )
    write_inc(
        ASSETS / "pallet_town_blk.inc",
        "pallet_town_blk",
        map_src.read_bytes(),
        "Pallet Town block map: 10×9 = 90 block IDs → [EBP+OW_MAP_GBADDR].",
    )
    # Connected maps' block data (for map-connection border strips).
    write_inc(
        ASSETS / "route1_blk.inc",
        "route1_blk",
        (ROOT / "maps" / "Route1.blk").read_bytes(),
        "Route 1 block map: 10×18 = 180 block IDs → [EBP+OW_ROUTE1_BLK_GBADDR]. "
        "North connection of Pallet Town.",
    )
    write_inc(
        ASSETS / "route21_blk.inc",
        "route21_blk",
        (ROOT / "maps" / "Route21.blk").read_bytes(),
        "Route 21 block map: 10×45 = 450 block IDs → [EBP+OW_ROUTE21_BLK_GBADDR]. "
        "South connection of Pallet Town.",
    )
    write_inc(
        ASSETS / "overworld_coll.inc",
        "overworld_coll",
        parse_coll_list(coll_src, "Overworld"),
        "Overworld tileset passable-tile list ($FF-terminated) → [EBP+OW_COLL_GBADDR].",
    )
    write_inc(
        ASSETS / "player_sprite.inc",
        "player_sprite",
        player_src.read_bytes(),
        "Red overworld sprite 2bpp (24 tiles; 0-11 = standing down/up/side) "
        "→ [EBP+GB_VCHARS0] ($8000, OBJ tile area).",
    )

    # NPC still tiles: first 192 bytes (12 tiles) of each sprite sheet.
    # imageBaseOffset N places tiles at (N-1)*12 in OBJ VRAM (byte addr $8000+(N-1)*12*16).
    for label, fname, base_offset in [
        ("npc_girl_still",   "girl",   3),   # imageBaseOffset 3 → tiles $18-$23 → $8180
        ("npc_fisher_still", "fisher", 4),   # imageBaseOffset 4 → tiles $24-$2F → $8240
        ("npc_oak_still",    "oak",    5),   # imageBaseOffset 5 → tiles $30-$3B → $8300
    ]:
        src = ROOT / "gfx" / "sprites" / f"{fname}.2bpp"
        tile_base = (base_offset - 1) * 12
        write_inc(
            ASSETS / f"{label}.inc",
            label,
            src.read_bytes()[:192],
            f"{fname} NPC still tiles (12 tiles, imageBaseOffset {base_offset}) "
            f"→ [EBP+GB_VCHARS0+0x{tile_base:02X}*16] (${0x8000 + tile_base * 16:04X}).",
        )

    print("done.")


if __name__ == "__main__":
    main()
