#!/usr/bin/env python3
"""Generate dos_port/assets/overworld_*.inc from repo binary assets.

Reads three binary files and writes NASM include files following the same
db-hex format used by gen_title_gfx_inc.py.

  overworld.2bpp   — built by 'make' in repo root (rgbgfx --trim-whitespace)
  overworld.bst    — checked-in blockset (128 blocks × 16 tile-IDs each)
  PalletTown.blk   — checked-in map (10×9 = 90 block IDs)

Run from the repo root:
    python3 tools/gen_overworld_assets.py

If overworld.2bpp is missing, run 'make' in the repo root first.
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ASSETS = ROOT / "dos_port" / "assets"


def write_inc(dst: Path, label: str, data: bytes, comment: str = ""):
    lines = [
        f"; {dst.name} — generated by tools/gen_overworld_assets.py.  DO NOT EDIT BY HAND.",
    ]
    if comment:
        lines.append(f"; {comment}")
    lines += ["", f"{label}:"]
    for i in range(0, len(data), 16):
        lines.append("    db " + ", ".join(f"0x{b:02X}" for b in data[i : i + 16]))
    size = len(data)
    lines += [
        f"{label}_end:",
        f"{label.upper()}_SIZE equ {label}_end - {label}",
        "",
    ]
    dst.write_text("\n".join(lines) + "\n")
    print(f"  wrote {dst} ({size} bytes)")


def main():
    gfx_src    = ROOT / "gfx" / "tilesets" / "overworld.2bpp"
    blocks_src = ROOT / "gfx" / "blocksets" / "overworld.bst"
    map_src    = ROOT / "maps" / "PalletTown.blk"

    if not gfx_src.exists():
        print(f"ERROR: {gfx_src} not found.", file=sys.stderr)
        print("Run 'make' in the repo root first to build .2bpp files.", file=sys.stderr)
        sys.exit(1)

    ASSETS.mkdir(parents=True, exist_ok=True)

    write_inc(
        ASSETS / "overworld_gfx.inc",
        "overworld_gfx",
        gfx_src.read_bytes(),
        "Overworld tileset 2bpp data → [EBP+OW_GFX_GBADDR] → vTileset ($9000).",
    )
    write_inc(
        ASSETS / "overworld_blocks.inc",
        "overworld_blocks",
        blocks_src.read_bytes(),
        "Overworld blockset: 128 blocks × 16 tile-IDs each → [EBP+OW_BLOCKS_GBADDR].",
    )
    write_inc(
        ASSETS / "pallet_town_blk.inc",
        "pallet_town_blk",
        map_src.read_bytes(),
        "Pallet Town block map: 10×9 = 90 block IDs → [EBP+OW_MAP_GBADDR].",
    )
    print("done.")


if __name__ == "__main__":
    main()
