name: Build ROM

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make gcc git build-essential

      - name: Install RGBDS Compiler
        run: |
          git clone https://github.com/gbdev/rgbds.git
          cd rgbds
          make
          sudo make install
          cd ..

      - name: Build Pokémon Yellow ROM
        run: |
          make

      - name: Upload Finished GBC ROM
        uses: actions/upload-artifact@v4
        with:
          name: pokeyellow-rom
          path: pokeyellow.gbc
